// Generated by scripts/gen-ios-migrations.mjs — DO NOT EDIT BY HAND.
// Source of truth: src/storage/migrations/*.sql (58 migrations).
// Re-run `node scripts/gen-ios-migrations.mjs` after adding a migration.

import Foundation

public enum SchemaMigrations {
    /// Every migration in declaration order. Each `sql` is the verbatim
    /// contents of the corresponding `src/storage/migrations/NNN_*.sql` file;
    /// `name` is the file name, used as the GRDB migration identifier so the
    /// applied-set is stable and matches the desktop `_migrations` keys.
    public static let all: [(name: String, sql: String)] = [
    (name: "001_init.sql", sql: #"""
-- ═══════════════════════════════════════════
-- Boardroom · initial schema
-- All tables for the v1 MVP. memory_* and knowledge_* are deferred
-- (post-MVP) and will land in a later migration.
-- ═══════════════════════════════════════════

-- User preferences · single-row table.
-- Note: the `theme` column is historical · appearance moved to
-- localStorage. The column stays defined here so existing rows
-- keep validating (NOT NULL DEFAULT), but the server code no
-- longer reads or writes it. Will be retired in a future cleanup
-- migration bundled with other DB-shape changes.
CREATE TABLE prefs (
  id          INTEGER PRIMARY KEY CHECK (id = 1),
  name        TEXT    NOT NULL DEFAULT 'You',
  intro       TEXT    NOT NULL DEFAULT '',
  avatar_seed TEXT,
  theme       TEXT    NOT NULL DEFAULT 'regent',
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
);

INSERT INTO prefs (id, name, intro, theme, created_at, updated_at)
VALUES (1, 'You', '', 'regent',
        CAST(strftime('%s','now') AS INTEGER) * 1000,
        CAST(strftime('%s','now') AS INTEGER) * 1000);

-- LLM provider API keys · stored AES-GCM encrypted.
CREATE TABLE provider_keys (
  provider   TEXT PRIMARY KEY,
  key_blob   BLOB NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

-- Directors / Agents.
CREATE TABLE agents (
  id          TEXT    PRIMARY KEY,
  name        TEXT    NOT NULL,
  handle      TEXT    UNIQUE NOT NULL,
  role_tag    TEXT    NOT NULL DEFAULT '',     -- e.g. 'skeptic', 'physicist'
  bio         TEXT    NOT NULL DEFAULT '',
  cover_quote TEXT,
  instruction TEXT    NOT NULL,
  model_v     TEXT    NOT NULL,                 -- 'sonnet-4-6' | 'gpt-5' | ...
  avatar_path TEXT    NOT NULL,
  is_pinned   INTEGER NOT NULL DEFAULT 0,
  is_seed     INTEGER NOT NULL DEFAULT 0,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
);

-- Rooms (boardroom sessions).
CREATE TABLE rooms (
  id           TEXT    PRIMARY KEY,
  number       INTEGER NOT NULL UNIQUE,
  name         TEXT    NOT NULL,
  subject      TEXT    NOT NULL,
  mode         TEXT    NOT NULL DEFAULT 'discovery',  -- discovery|constructive|adversarial
  status       TEXT    NOT NULL DEFAULT 'live',       -- live|adjourned
  brief_style  TEXT,
  created_at   INTEGER NOT NULL,
  adjourned_at INTEGER
);

-- Room ↔ Agent membership (M:N).
CREATE TABLE room_members (
  room_id   TEXT    NOT NULL,
  agent_id  TEXT    NOT NULL,
  position  INTEGER NOT NULL,                     -- speaking order in round-robin
  joined_at INTEGER NOT NULL,
  PRIMARY KEY (room_id, agent_id),
  FOREIGN KEY (room_id)  REFERENCES rooms(id)  ON DELETE CASCADE,
  FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE INDEX idx_room_members_room ON room_members(room_id, position);

-- Messages (user, agents, system).
CREATE TABLE messages (
  id           TEXT    PRIMARY KEY,
  room_id      TEXT    NOT NULL,
  author_kind  TEXT    NOT NULL,                  -- 'agent' | 'user' | 'system'
  author_id    TEXT,                              -- agent.id or NULL
  reply_to_id  TEXT,
  body         TEXT    NOT NULL,
  meta_json    TEXT,                              -- JSON: mentions[], speakerStatus, ...
  round_num    INTEGER NOT NULL DEFAULT 1,
  created_at   INTEGER NOT NULL,
  FOREIGN KEY (room_id)     REFERENCES rooms(id)     ON DELETE CASCADE,
  FOREIGN KEY (reply_to_id) REFERENCES messages(id)  ON DELETE SET NULL
);

CREATE INDEX idx_messages_room ON messages(room_id, created_at);

-- Configuration / lifecycle events (room-opened, room-adjourned, member-add, ...).
CREATE TABLE config_events (
  id          TEXT    PRIMARY KEY,
  room_id     TEXT    NOT NULL,
  kind        TEXT    NOT NULL,
  payload     TEXT,                                -- JSON
  actor_kind  TEXT    NOT NULL,                    -- 'user' | 'system'
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

-- Briefs · adjourn product.
CREATE TABLE briefs (
  id          TEXT    PRIMARY KEY,
  room_id     TEXT    NOT NULL UNIQUE,
  style       TEXT    NOT NULL,
  title       TEXT    NOT NULL,
  body_md     TEXT    NOT NULL,
  body_json   TEXT,
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

"""#),
    (name: "002_default_opus.sql", sql: #"""
-- ═══════════════════════════════════════════
-- Default seeded directors switch to Opus 4.7.
-- Only agents that are still on the prior default (`sonnet-4-6`) AND were
-- originally seeded by Boardroom (is_seed = 1) get bumped — any agent the
-- user has explicitly customized is left alone.
-- ═══════════════════════════════════════════

UPDATE agents
SET model_v = 'opus-4-7',
    updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000
WHERE is_seed = 1 AND model_v = 'sonnet-4-6';

"""#),
    (name: "003_paused_at.sql", sql: #"""
-- Add paused_at column for the paused room status.
ALTER TABLE rooms ADD COLUMN paused_at INTEGER;

"""#),
    (name: "004_room_intensity.sql", sql: #"""
-- Add intensity column for the calm | sharp | brutal slider on convene.
-- 'sharp' is the prototype default.
ALTER TABLE rooms ADD COLUMN intensity TEXT NOT NULL DEFAULT 'sharp';

"""#),
    (name: "005_chair.sql", sql: #"""
-- Adds the Chair role: a special always-on agent that opens with a
-- clarification, ends each round with key-points + a vote prompt,
-- announces config changes, and writes the closing brief.
--
-- The chair is modeled as a regular agent with role_kind = 'moderator'
-- so we can reuse the message + streaming pipeline.

ALTER TABLE agents ADD COLUMN role_kind TEXT NOT NULL DEFAULT 'director';

-- Key points: the chair generates 3 of these at the end of each round.
-- Users vote up/down; voted points feed back into the next director
-- system prompt as user-interest signals.
CREATE TABLE key_points (
  id          TEXT    PRIMARY KEY,
  room_id     TEXT    NOT NULL,
  message_id  TEXT,                                    -- round-end chair message that introduced these
  round_num   INTEGER NOT NULL,
  body        TEXT    NOT NULL,
  vote        TEXT,                                     -- 'up' | 'down' | NULL
  position    INTEGER NOT NULL,                         -- 0/1/2 ordering
  created_at  INTEGER NOT NULL,
  voted_at    INTEGER,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);
CREATE INDEX idx_key_points_room ON key_points(room_id);
CREATE INDEX idx_key_points_round ON key_points(room_id, round_num);

-- Soft pause flag: set when the chair finishes a round-end message.
-- The orchestrator won't dispatch the next director until the user
-- clicks Continue (or Adjourn).
ALTER TABLE rooms ADD COLUMN awaiting_continue INTEGER NOT NULL DEFAULT 0;

"""#),
    (name: "006_awaiting_clarify.sql", sql: #"""
-- Soft pause for the chair's opening clarification phase. While set, the
-- orchestrator routes user replies through the chair instead of the
-- director queue, so the chair can ask multiple follow-up questions
-- before releasing the directors. Capped at 3 chair turns by the
-- orchestrator to prevent unbounded loops.
ALTER TABLE rooms ADD COLUMN awaiting_clarify INTEGER NOT NULL DEFAULT 0;

"""#),
    (name: "007_agent_tokens.sql", sql: #"""
-- Track cumulative tokens consumed by each agent across every LLM
-- turn they've been the speaker for. Counted from the Vercel AI SDK's
-- usage report when each director / chair stream finishes — see
-- src/orchestrator/room.ts. Rooms-joined and rounds-spoken are
-- derived on read (room_members count, distinct round_num count).
ALTER TABLE agents ADD COLUMN tokens_consumed INTEGER NOT NULL DEFAULT 0;

"""#),
    (name: "008_agent_memories.sql", sql: #"""
-- Long-term agent memory · per-agent notes about the USER that
-- accumulate across rooms. Each agent (directors + chair) keeps an
-- independent set so multi-perspective lenses stay distinct (Skeptic
-- vs Empath remember different things). Read back into every prompt
-- as a "Known about the user" block; written at room adjourn via a
-- small extraction LLM call (skipped when room.incognito = 1).
--
-- This is NOT room memory. Room-scoped context (chat history, key
-- points, brief) is already covered by the existing tables — we're
-- only adding the cross-room layer here.

CREATE TABLE IF NOT EXISTS agent_memories (
  id            TEXT PRIMARY KEY,
  agent_id      TEXT NOT NULL,
  content       TEXT NOT NULL,
  -- "fact"        · stable assertion ("user is cofounder at HR SaaS")
  -- "observation" · agent's read on the user ("user defines terms loosely")
  -- "preference"  · style / format / language pref
  -- "goal"        · stated objective with horizon
  kind          TEXT NOT NULL DEFAULT 'fact',
  -- "extracted"   · auto-written at room adjourn
  -- "user_added"  · manually entered via agent profile
  -- "user_pinned" · automatic flag set when user pins (denormalised mirror of `pinned`)
  source        TEXT NOT NULL DEFAULT 'extracted',
  -- room this memory was distilled from (NULL when user added manually)
  source_room   TEXT,
  -- LLM-self-reported confidence at extraction time (0..1)
  confidence    REAL NOT NULL DEFAULT 0.7,
  -- Pinned memories are ALWAYS injected into prompts; non-pinned go
  -- through a recency cap.
  pinned        INTEGER NOT NULL DEFAULT 0,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
  FOREIGN KEY (source_room) REFERENCES rooms(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_memories_agent ON agent_memories(agent_id, pinned DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_memories_room ON agent_memories(source_room);

-- Per-room incognito flag · when set, room adjourn does NOT trigger
-- extraction and nothing from the room flows into long-term memory.
-- Default 0 (writes by default, per the v1 product decision).
ALTER TABLE rooms ADD COLUMN incognito INTEGER NOT NULL DEFAULT 0;

"""#),
    (name: "009_skills.sql", sql: #"""
-- Per-agent skill catalog. Skills are installed by uploading a Skill.md
-- file with YAML frontmatter (name, slug, description, when_to_use,
-- ability deltas, tips) plus a free markdown body. The body is only
-- injected into the agent's Pass-2 system prompt when the Pass-1 router
-- picks the skill for that turn (Claude Code-style progressive
-- disclosure). Per-agent storage in v1 — no shared library.
CREATE TABLE IF NOT EXISTS agent_skills (
  id           TEXT PRIMARY KEY,
  agent_id     TEXT NOT NULL,
  slug         TEXT NOT NULL,
  name         TEXT NOT NULL,
  version      TEXT NOT NULL DEFAULT '1.0',
  description  TEXT NOT NULL,
  when_to_use  TEXT NOT NULL,
  body_md      TEXT NOT NULL,
  ability_json TEXT NOT NULL DEFAULT '{}',
  tips_json    TEXT NOT NULL DEFAULT '[]',
  created_at   INTEGER NOT NULL,
  updated_at   INTEGER NOT NULL,
  UNIQUE (agent_id, slug),
  FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_agent_skills_agent ON agent_skills (agent_id);

"""#),
    (name: "010_briefs_multi.sql", sql: #"""
-- Multiple briefs per room. Previously the briefs table had `room_id
-- NOT NULL UNIQUE`, enforcing a single deliverable per room with a
-- regenerate-overwrites-original UX. The new model preserves history:
-- the first brief is generated on adjourn; each "Add a perspective"
-- regeneration appends a new row. The user can switch between briefs
-- via a tab strip in the brief card and the report viewer.
--
-- Also adds an optional `supplement` column to record the user's input
-- when a brief was a regeneration (the first brief has supplement = NULL).
--
-- SQLite can't DROP a UNIQUE constraint in place, so we rebuild the
-- table. The migration runner already wraps each migration in a
-- transaction, so no explicit BEGIN/COMMIT here.

CREATE TABLE briefs_new (
  id          TEXT    PRIMARY KEY,
  room_id     TEXT    NOT NULL,
  style       TEXT    NOT NULL,
  title       TEXT    NOT NULL,
  body_md     TEXT    NOT NULL,
  body_json   TEXT,
  supplement  TEXT,
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

INSERT INTO briefs_new (id, room_id, style, title, body_md, body_json, supplement, created_at)
SELECT id, room_id, style, title, body_md, body_json, NULL, created_at FROM briefs;

DROP TABLE briefs;
ALTER TABLE briefs_new RENAME TO briefs;

-- Fast lookup of the latest brief for a room (newest first).
CREATE INDEX idx_briefs_room_created ON briefs(room_id, created_at DESC);

"""#),
    (name: "011_agent_ability.sql", sql: #"""
-- Per-agent base ability profile (radar chart).
-- Stored as JSON: {"dissent": N, "pattern_recall": N, "rigor": N,
-- "empathy": N, "narrative": N, "decisiveness": N} where each N is in
-- 0..10. NULL means "no profile set" — radar falls back to flat 5/all
-- (legacy behaviour). New AI-generated directors carry a profile
-- inferred from their description so the radar reflects personality.
ALTER TABLE agents ADD COLUMN ability_json TEXT;

"""#),
    (name: "012_brief_composer.sql", sql: #"""
-- Report composer · capture the chair's component picks alongside each
-- brief. Today every report is a fixed McKinsey-style 12-section deck;
-- the new flow has a Stage 1.5 composer that picks (a) a style spine
-- and (b) a subset of components based on the room's subject and the
-- per-director signals.
--
-- Columns:
--   spine                Renderer key. v1 ships with `boardroom-dark`
--                        only; later releases add `a16z-thesis`,
--                        `anthropic-essay`, `gartner-note`,
--                        `mckinsey-deck`, `openai-paper`. Default keeps
--                        legacy briefs renderable.
--   components_json      JSON array of { kind, order } objects. Empty
--                        array means "legacy / all 12 components" — the
--                        renderer falls back to today's static layout.
--   composer_rationale   The composer's one-line explanation, surfaced
--                        on hover of the SPINE tag in the UI. NULL when
--                        the composer was bypassed.
--   subject_type         Coarse classification the composer assigned
--                        (e.g. `investment-judgement`, `philosophical`,
--                        `option-comparison`). Used by analytics + by
--                        future "regenerate as" presets. NULL for legacy.

ALTER TABLE briefs ADD COLUMN spine              TEXT NOT NULL DEFAULT 'boardroom-dark';
ALTER TABLE briefs ADD COLUMN components_json    TEXT NOT NULL DEFAULT '[]';
ALTER TABLE briefs ADD COLUMN composer_rationale TEXT;
ALTER TABLE briefs ADD COLUMN subject_type       TEXT;

"""#),
    (name: "013_retired_token_usage.sql", sql: #"""
-- Token usage rollup for deleted custom agents.
--
-- When a user deletes a custom agent, the row is removed from the
-- `agents` table — but the LLM calls that agent already made were real:
-- the user already paid for those tokens, and the Usage panel's totals
-- become a lie if they silently disappear.
--
-- Before each `DELETE FROM agents`, the storage layer transfers the
-- agent's `tokens_consumed` into this rollup table, keyed by model.
-- Per-agent identity is intentionally lost (deletion = "make it go
-- away"), but the model rollup and the grand total stay honest.
--
-- Columns:
--   model_v     The model the retired agents used. Multiple deleted
--               agents that shared a model collapse into one row.
--   tokens      Cumulative tokens billed against retired agents on
--               this model.
--   agents      Number of agents folded into this row (used by the
--               UI to surface "+ N retired agents · X tokens").
--   updated_at  Last time a deletion landed here.

CREATE TABLE retired_token_usage (
  model_v     TEXT    PRIMARY KEY,
  tokens      INTEGER NOT NULL DEFAULT 0,
  agents      INTEGER NOT NULL DEFAULT 0,
  updated_at  INTEGER NOT NULL
);

"""#),
    (name: "014_agent_web_search.sql", sql: #"""
-- Per-agent web-search toggle.
--
-- Default 1 (enabled). The actual gate is the user-supplied Brave
-- Search API key in `provider_keys` — without that key, no agent
-- can search regardless of this flag. With the key set, every agent
-- is search-capable by default; the user can switch any individual
-- director off via the agent profile page (e.g. to keep one
-- director on first-principles only).

ALTER TABLE agents ADD COLUMN web_search_enabled INTEGER NOT NULL DEFAULT 1;

"""#),
    (name: "015_web_search_default_off.sql", sql: #"""
-- Reset every agent's Web Search flag to OFF.
--
-- Migration 014 introduced the column with `DEFAULT 1` because the
-- gating model at that point was "global key gates everything; per-
-- agent toggle is a fine-tune". After the first round of UX feedback
-- we flipped the philosophy: the default experience should be no
-- search, with the user opting in TWICE — once globally (configuring
-- the Brave key in Preferences) and once per-agent (flipping the
-- toggle on the director's profile).
--
-- This migration only resets the row values. The column DEFAULT in
-- the schema stays at 1 because changing it requires a SQLite full
-- table rebuild; the application layer (`insertAgent`) explicitly
-- writes 0 for newly created agents going forward.

UPDATE agents SET web_search_enabled = 0;

"""#),
    (name: "016_prefs_default_model.sql", sql: #"""
-- Global default model · the modelV new agents inherit at create time
-- and the runtime fallback when an agent's stored modelV becomes
-- unreachable (user revoked the underlying API key). NULL on legacy
-- rows; the availability layer's `defaultModelFor()` helper picks a
-- sensible value at first use and the prefs row gets back-filled.
ALTER TABLE prefs ADD COLUMN default_model_v TEXT;

"""#),
    (name: "017_agent_carrier_pref.sql", sql: #"""
-- Per-agent carrier preference.
--
-- The same modelV (e.g. "gpt-5-5") may be reachable via multiple
-- carriers when the user has more than one provider key configured —
-- e.g. OpenRouter (`google/gpt-5.5`) vs OpenAI direct (`gpt-5.5`).
-- The adapter's default precedence rules pick one carrier; this column
-- lets each agent override that pick. NULL means "use the default
-- precedence" (the prior behavior). Values: 'openrouter' | 'anthropic'
-- | 'openai' | 'google' | 'xai'. Validation lives in the application
-- layer; SQLite isn't asked to enforce the enum.
ALTER TABLE agents ADD COLUMN carrier_pref TEXT;

"""#),
    (name: "018_brief_house_style.sql", sql: #"""
-- House style preset · captures the editorial / structural register the
-- composer picked for this brief, alongside the existing spine (visual
-- CSS) and components_json (per-component picks). The same components
-- can render under different house styles with different section
-- vocabulary and voice — `sequoia-memo` and `stanford-research` share
-- the recommendations component but rename it to "## What Would Make
-- This Work" vs "## Future Work" and shift voice from declarative to
-- hedged.
--
-- Default keeps legacy briefs renderable (`boardroom-default` is the
-- existing behaviour: default English labels, neutral voice).
ALTER TABLE briefs ADD COLUMN house_style TEXT NOT NULL DEFAULT 'boardroom-default';

"""#),
    (name: "019_room_summaries.sql", sql: #"""
-- Hierarchical summarization · per-room cached summaries used by the
-- director-context assembler to stay under context-window pressure on
-- long rooms without dropping continuity.
--
-- Tier model:
--   level=1 · per-round narrative, generated once when the round drops
--            out of the L0 (verbatim) window. round_num identifies which
--            round this summary represents.
--   level=2 · rolling consolidated summary of all rounds older than the
--            L1 window. start_round + end_round describe the range it
--            covers; regenerated when a new L1 row gets folded in.
--
-- A row's `body` is plain narrative text (not key-points, not JSON);
-- the assembler concatenates it directly into the system prompt under
-- a "// EARLIER IN THIS ROOM" header.
--
-- `source_hash` lets future invalidation logic detect whether the
-- inputs changed (e.g. a new message inserted into an old round); for
-- v1 we only generate forward, so the hash is informational.
CREATE TABLE IF NOT EXISTS room_summaries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room_id TEXT NOT NULL,
  level INTEGER NOT NULL CHECK (level IN (1, 2)),
  round_num INTEGER,            -- L1: the round this summary represents; L2: NULL
  start_round INTEGER,          -- L2: oldest round covered; L1: same as round_num
  end_round INTEGER,            -- L2: newest round covered; L1: same as round_num
  body TEXT NOT NULL,
  model_v TEXT,                 -- which utility model generated this row
  source_hash TEXT,             -- hash of the input chunk(s); v2 invalidation hook
  created_at INTEGER NOT NULL,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

-- One L1 row per (room, round). One L2 row per room at any moment.
CREATE UNIQUE INDEX IF NOT EXISTS idx_room_summaries_l1 ON room_summaries(room_id, level, round_num) WHERE level = 1;
CREATE UNIQUE INDEX IF NOT EXISTS idx_room_summaries_l2 ON room_summaries(room_id, level) WHERE level = 2;

-- Read path: assembler queries by room + level.
CREATE INDEX IF NOT EXISTS idx_room_summaries_room_level ON room_summaries(room_id, level);

"""#),
    (name: "020_room_followup.sql", sql: #"""
-- Follow-up rooms · "Convene a follow-up" feature
--
-- A room can be started as a continuation of a prior adjourned room.
-- Two reference columns are added:
--
--   parent_room_id  · the prior room being followed up. Both rooms
--                     remain independent (own messages, own briefs);
--                     the link is purely a reference for navigation
--                     and for context injection at director-prompt
--                     build time.
--   parent_brief_id · which specific brief the follow-up is scoped
--                     to. A parent room can carry multiple briefs
--                     (regenerations); the orchestrator uses this id
--                     to load exactly that brief's markdown + signal
--                     attribution into the new room's director system
--                     prompts.
--
-- Both nullable so existing standalone rooms keep working unchanged.
-- No FK constraints — parent rooms can be deleted independently
-- (the follow-up degrades gracefully into "orphan follow-up" with
-- the link nulled at read time if the parent disappears).

ALTER TABLE rooms ADD COLUMN parent_room_id  TEXT NULL;
ALTER TABLE rooms ADD COLUMN parent_brief_id TEXT NULL;

-- Persist Stage-1 per-director signals on the brief row so a
-- follow-up room can re-use the prior session's named-by-lens
-- observations without re-running the haiku extract pass. The
-- field carries a JSON array of { directorId, directorName,
-- signals: [{ text, lens, sources }] } — same shape the brief
-- orchestrator's Stage 2 receives. NULL on legacy briefs (the
-- follow-up reader falls back to brief markdown alone).
ALTER TABLE briefs ADD COLUMN signals_json TEXT NULL;

"""#),
    (name: "021_notes.sql", sql: #"""
-- Chairman's notes · user-curated excerpts saved while reading
-- director output. The user selects a span of text inside a director
-- message, hits "+ Save" or the `S` shortcut, and we persist:
--
--   quote_text     · the exact selection (renders bolded in the
--                    note card and gets the dotted-underline overlay
--                    when the source room is re-opened)
--   context_before · ~1–2 sentences of the director's text immediately
--                    before the selection · displayed faded to give
--                    re-reading context, never displayed without the
--                    quote
--   context_after  · same, after the selection
--   char_offset_start / char_offset_end · the selection's position
--                    inside the rendered message body, used by the
--                    in-room highlight overlay to wrap the same span
--                    in <span class="note-highlight"> on next render
--
-- Source linkage is room_id + message_id (no FKs · briefs/messages can
-- be removed independently and notes degrade to "orphan" with the
-- source link nulled at read time).
--
-- author_kind / author_name / author_id snapshot the director's
-- identity at save-time so cards in the All Notes view can render
-- "ROOM #N · DirectorName · time" without joining live agents (which
-- may have been renamed or deleted since).

CREATE TABLE IF NOT EXISTS notes (
  id                 TEXT PRIMARY KEY,
  room_id            TEXT NOT NULL,
  message_id         TEXT NOT NULL,
  author_kind        TEXT NOT NULL,
  author_id          TEXT NULL,
  author_name        TEXT NOT NULL,
  quote_text         TEXT NOT NULL,
  context_before     TEXT NOT NULL DEFAULT '',
  context_after      TEXT NOT NULL DEFAULT '',
  char_offset_start  INTEGER NOT NULL,
  char_offset_end    INTEGER NOT NULL,
  -- Deferred-action fields · written via PATCH after the user opens
  -- the card and decides to annotate / tag / mark as acted-on. NULL
  -- on a fresh save (the MVP capture flow only fills the columns
  -- above).
  user_note          TEXT NULL,
  tags_json          TEXT NULL,
  status             TEXT NOT NULL DEFAULT 'open',  -- open | acted | archived
  created_at         INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notes_room       ON notes(room_id);
CREATE INDEX IF NOT EXISTS idx_notes_message    ON notes(message_id);
CREATE INDEX IF NOT EXISTS idx_notes_created_at ON notes(created_at DESC);

"""#),
    (name: "022_intensity_brutal_to_terse.sql", sql: #"""
-- Rename intensity value `brutal` → `terse`.
--
-- The original `brutal` label was misleading: it suggested an adversarial
-- dial (read by many users as "harshness"), but the prompt-construction
-- layer treats intensity as a pure cadence axis (length / hedge quantity /
-- packaging) — orthogonal to the adversarial axis (mode / tone). Users
-- reaching for "brutal" hoping for sharper disagreements were instead
-- getting shorter responses without the additional pushback they wanted.
--
-- The replacement `terse` accurately describes the cadence outcome
-- ("telegraphic, one sentence per turn") without leaking onto the
-- adversarial axis. This migration rewrites existing rows; the prompt
-- builder also normalizes any stale `brutal` at read time as a belt-
-- and-suspenders safety net for in-flight imports / API clients.
UPDATE rooms SET intensity = 'terse' WHERE intensity = 'brutal';

"""#),
    (name: "023_brief_assets.sql", sql: #"""
-- 023_brief_assets · rename signals_json → assets_json on briefs.
--
-- Stage 1 of the brief pipeline produces a richer 9-field asset bundle
-- per director (claims / evidence / tensions / assumptions / risks /
-- opportunities / actions / quotes / openQuestions) instead of the
-- legacy 2-4 flat signals list. The persisted column for this
-- structured material is renamed to assets_json. Rows that carry the
-- old signals_json shape are intentionally NOT migrated in place — the
-- old shape isn't a subset of the new one (no `claims` / `evidence` /
-- etc. fields), so re-using the column with a shape change would mean
-- every old row reads as parse failure → null assets. Cleaner to drop
-- the old column and start fresh; old briefs simply lose the persisted
-- signals (their markdown body is intact, follow-up rooms just fall
-- back to brief markdown for prior context, same as briefs filed
-- before signals_json existed).
--
-- SQLite doesn't support DROP COLUMN before 3.35 in a way we can rely
-- on. Use the standard recreate-and-copy dance: rename the table,
-- recreate with the new column, copy preserved fields over, drop old.
-- The components_json / composer_rationale / subject_type / house_style
-- columns from earlier migrations are all preserved.

-- Recreate-and-copy under FK enforcement requires temporarily disabling
-- foreign-key checks so DROP TABLE briefs__old doesn't cascade-delete
-- referenced rows. PRAGMA foreign_keys takes effect outside transactions
-- in SQLite — but the migration runner already turned FKs ON at
-- connection open. Toggling within the migration is the standard
-- recreate-and-copy pattern (see SQLite docs § "Making Other Kinds of
-- Table Schema Changes"). The PRAGMA reverts to its prior value when
-- the transaction commits, so the next migration / connection sees
-- foreign_keys = ON again.
PRAGMA foreign_keys = OFF;

ALTER TABLE briefs RENAME TO briefs__old;

CREATE TABLE briefs (
  id                  TEXT PRIMARY KEY,
  room_id             TEXT NOT NULL,
  style               TEXT NOT NULL,
  title               TEXT NOT NULL,
  body_md             TEXT NOT NULL,
  body_json           TEXT,
  supplement          TEXT,
  spine               TEXT NOT NULL DEFAULT 'boardroom-dark',
  components_json     TEXT NOT NULL DEFAULT '[]',
  composer_rationale  TEXT,
  subject_type        TEXT,
  house_style         TEXT NOT NULL DEFAULT 'boardroom-default',
  assets_json         TEXT,
  created_at          INTEGER NOT NULL,
  FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

INSERT INTO briefs (
  id, room_id, style, title, body_md, body_json, supplement,
  spine, components_json, composer_rationale, subject_type, house_style,
  assets_json, created_at
)
SELECT
  id, room_id, style, title, body_md, body_json, supplement,
  spine, components_json, composer_rationale, subject_type, house_style,
  NULL,                  -- legacy signals_json drops on the floor
  created_at
FROM briefs__old;

DROP TABLE briefs__old;

-- Restore the index from migration 010 (briefs(room_id, created_at DESC))
-- under its original name so query plans remain stable across the rename.
CREATE INDEX IF NOT EXISTS idx_briefs_room_created ON briefs(room_id, created_at DESC);

PRAGMA foreign_keys = ON;

"""#),
    (name: "024_usage_daily.sql", sql: #"""
-- Daily-granularity token usage log · the cumulative `agents.tokens_consumed`
-- column stays the canonical "All / lifetime" total, but the user-settings
-- Usage panel now also renders a 14-day stacked bar chart that needs
-- per-day-per-model resolution. This table is the source for that chart.
--
-- Granularity: (day · agent_id · model_v).
--   day      · 'YYYY-MM-DD' formatted in the server's local time at
--              billing time. Local-first software running on the user's
--              own machine, so wall-clock matches their intuition of
--              "today" without TZ gymnastics on the client.
--   agent_id · who actually spoke that day (the column the UI uses to
--              render per-agent rows in the day's drill-down).
--   model_v  · SNAPSHOT at billing time. If the user reassigns an
--              agent's model later, that day's history stays tied to
--              the model that actually ran — without this, all of an
--              agent's history would silently re-skin under the new
--              model on next chart render.
--
-- Writes happen atomically alongside the `agents.tokens_consumed`
-- update in `incrementAgentTokens()` (UPSERT here, UPDATE there, single
-- transaction). Single chokepoint; every billing path (director turns,
-- chair turns, brief stages 1/1.5/2/3) flows through it.
--
-- No backfill: pre-migration cumulative stays in `agents.tokens_consumed`
-- and continues to drive the "All · cumulative" view in the UI. Day-level
-- history begins from migration day; days before that render as empty
-- bars in the 14-day chart.

CREATE TABLE IF NOT EXISTS usage_daily (
  day      TEXT    NOT NULL,
  agent_id TEXT    NOT NULL,
  model_v  TEXT    NOT NULL,
  tokens   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, agent_id, model_v)
);

-- Day-only index for the 14-day window query (`WHERE day >= ?`). The
-- composite primary key already covers (day, agent_id, ...) in lookup
-- order so the per-row UPSERT path doesn't need a separate index.
CREATE INDEX IF NOT EXISTS usage_daily_day ON usage_daily(day);

"""#),
    (name: "025_brief_mode.sql", sql: #"""
-- 025_brief_mode · add `mode` column to briefs.
--
-- Briefs now come in two flavors:
--   · 'research-note' (default · the existing markdown-body research
--     dossier with composer-picked components and a spine-rendered
--     report.html view)
--   · 'bento' (new · a single-page infographic with fixed structure ·
--     header band, 3-milestone timeline, ranked-bars / verification /
--     talking-points sidebars, conclusion band · rendered by bento.html
--     from the BentoScaffold JSON persisted in body_json)
--
-- Legacy rows pre-dating bento are research-note by definition; the
-- DEFAULT clause backfills them. The column is NOT NULL so the
-- pipeline can branch on it without an `?? "research-note"` fallback
-- at every read site.
--
-- For 'bento' rows the body_md column is empty (or carries a plain-
-- text fallback) and body_json holds the structured BentoScaffold; the
-- spine / components_json / composer_rationale columns are unused (the
-- bento has fixed shape, the composer doesn't run for it).

ALTER TABLE briefs ADD COLUMN mode TEXT NOT NULL DEFAULT 'research-note';

"""#),
    (name: "026_memory_metabolism.sql", sql: #"""
-- Memory metabolism · Sleep / Dreaming Mode infrastructure (Phase 1).
--
-- Three forward-compatible additions to agent_memories that let a
-- periodic "dream" pass decide which memories to keep, decay, or
-- promote to long-term.  Phase 1 only uses `usage_count` /
-- `last_used_at` (decay heuristic) and `tier` (default 'short' for
-- everything pre-existing). The remaining columns (superseded_by,
-- consolidated_from, provenance_rooms) plus the agent_dreams audit
-- table land in the Phase 2 migration.
--
-- Rationale per column:
--   · tier         · 'short' / 'long' · stable cross-room patterns
--                    promote out of the recency cap (tier='long' is
--                    always injected into prompts; 'short' goes
--                    through the top-N recency window).
--   · usage_count  · how many times this memory has been injected
--                    into a director's prompt. Memories that ARE
--                    being read escape the decay sweep — only
--                    genuinely-forgotten rows get culled.
--   · last_used_at · timestamp of most recent injection. Lets
--                    future tier-promotion rules consider "freshness
--                    of relevance" separately from "freshness of
--                    creation."

ALTER TABLE agent_memories ADD COLUMN tier         TEXT    NOT NULL DEFAULT 'short';
ALTER TABLE agent_memories ADD COLUMN usage_count  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agent_memories ADD COLUMN last_used_at INTEGER;

-- Tier-aware retrieval · listTier(agentId, tier) reads through this
-- index when memoriesForContext composes the prompt-injection set.
CREATE INDEX IF NOT EXISTS idx_agent_memories_tier
  ON agent_memories(agent_id, tier, pinned DESC, created_at DESC);

"""#),
    (name: "027_memory_metabolism_p2.sql", sql: #"""
-- Memory metabolism · Phase 2 schema · supersession / consolidation
-- audit + dream-cycle log.
--
-- Three additions to agent_memories let the LLM dream pipeline:
--   · merge near-duplicates without losing the originals (the canonical
--     merged memory points back at its sources via consolidated_from;
--     each source is marked superseded_by → the merged row).
--   · resolve contradictions by superseding the older claim with the
--     newer one (audit pointer survives, prompt-injection filter
--     drops it).
--   · weight stable cross-room patterns for promotion to tier='long'
--     via a count of distinct rooms that reinforced the memory.
--
-- The agent_dreams table is the audit log · one row per cycle so we
-- can surface "last dream 2h ago · dropped 3, merged 4" in the UI
-- and grep stderr-equivalent metrics out of the DB.
--
-- Phase 1 columns (tier / usage_count / last_used_at) were added in
-- migration 026; this migration assumes those are present.

ALTER TABLE agent_memories ADD COLUMN superseded_by      TEXT REFERENCES agent_memories(id) ON DELETE SET NULL;
ALTER TABLE agent_memories ADD COLUMN consolidated_from  TEXT;     -- JSON array of source memory ids
ALTER TABLE agent_memories ADD COLUMN provenance_rooms   INTEGER NOT NULL DEFAULT 1;

-- Index on (agent, superseded) so retrieval can quickly skip
-- consolidated/superseded rows. Also benefits "list forgotten"
-- audit views.
CREATE INDEX IF NOT EXISTS idx_agent_memories_superseded
  ON agent_memories(agent_id, superseded_by);

CREATE TABLE IF NOT EXISTS agent_dreams (
  id           TEXT    PRIMARY KEY,
  agent_id     TEXT    NOT NULL,
  started_at   INTEGER NOT NULL,
  finished_at  INTEGER,
  before_count INTEGER NOT NULL,
  after_count  INTEGER,
  decayed      INTEGER NOT NULL DEFAULT 0,
  merged       INTEGER NOT NULL DEFAULT 0,
  promoted     INTEGER NOT NULL DEFAULT 0,
  superseded   INTEGER NOT NULL DEFAULT 0,
  notes        TEXT,
  FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dreams_agent_recent
  ON agent_dreams(agent_id, started_at DESC);

"""#),
    (name: "028_voice_mode.sql", sql: #"""
-- Voice mode · per-room delivery mode and per-agent TTS voice profile.
-- `delivery_mode = voice` switches director prompts and orchestrator pacing.
-- `agents.voice_json` stores provider/model/voiceId/speed/pitch/volume/instructions.
ALTER TABLE rooms ADD COLUMN delivery_mode TEXT NOT NULL DEFAULT 'text';
ALTER TABLE agents ADD COLUMN voice_json TEXT;

"""#),
    (name: "029_web_search_provider_pref.sql", sql: #"""
-- When both Brave Search and Tavily API keys exist, picks which backend
-- serves Web Search turns. Single-key setups ignore this · the active
-- backend is inferred from whichever key is present.
ALTER TABLE prefs ADD COLUMN web_search_provider TEXT NOT NULL DEFAULT 'brave';

"""#),
    (name: "030_minimax_region.sql", sql: #"""
-- MiniMax API region preference.
-- "cn" = China mainland (api.minimaxi.com)
-- "intl" = International (api.minimax.io)
-- Default "cn" because the China endpoint is more commonly used.
ALTER TABLE prefs ADD COLUMN minimax_region TEXT NOT NULL DEFAULT 'cn';

"""#),
    (name: "031_agent_persona_spec.sql", sql: #"""
-- 029_agent_persona_spec · Full Persona Replication mode
--
-- Two surfaces:
--
-- (1) `agents.persona_spec_json` · the deep persona artifact for
--     directors built via the new "Full persona" flow. Holds the
--     7-phase output (spec / knowledge context / behavioural rules /
--     few-shot examples / reflection checklist / eval set + build
--     report). Compiled into the `instruction` column at save time so
--     existing readers (brief Stage 1, chair, room orchestration)
--     stay backward-compatible with no consumer changes.
--
--     NULL on every existing agent (Signal-mode default) and on every
--     seeded director — those flows render unchanged. The runtime
--     few-shot + reflection-checklist injection in prompt.ts is
--     gated on `persona_spec_json IS NOT NULL`, so non-Full agents
--     don't pay the per-turn token cost.
--
-- (2) `agent_persona_jobs` · one row per in-flight or completed Full-
--     persona build. Persisted at phase boundaries so a tab close /
--     SSE disconnect can resume from the last completed phase. Server
--     restart marks `running` jobs as `failed` (mid-LLM-call resume
--     isn't realistic) and surfaces a retry path.
--
--     Tokens are tracked here until the user clicks Save — at that
--     point they flush via `incrementAgentTokens(newAgentId, total)`
--     so usage stats credit the agent the user actually ended up
--     creating. Aborted / failed jobs absorb the cost (no synthetic
--     `__persona_builder__` agent to seed and reconcile).

ALTER TABLE agents ADD COLUMN persona_spec_json TEXT;

CREATE TABLE IF NOT EXISTS agent_persona_jobs (
  id            TEXT PRIMARY KEY,
  description   TEXT NOT NULL,
  mode          TEXT NOT NULL DEFAULT 'full',  -- 'full' (only mode persisted; 'signal' is in-memory)
  status        TEXT NOT NULL,                 -- 'running' | 'done' | 'failed' | 'aborted'
  current_phase INTEGER NOT NULL DEFAULT 1,    -- 1..7
  progress_pct  INTEGER NOT NULL DEFAULT 0,    -- 0..100, monotonic
  partial_json  TEXT,                          -- accumulated phase outputs (JSON)
  agent_id      TEXT,                          -- set after the user clicks Save
  prompt_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  started_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  error         TEXT
);

CREATE INDEX IF NOT EXISTS agent_persona_jobs_status ON agent_persona_jobs(status);
CREATE INDEX IF NOT EXISTS agent_persona_jobs_started_at ON agent_persona_jobs(started_at DESC);

"""#),
    (name: "032_room_vote_trigger.sql", sql: #"""
-- Per-room vote-trigger preference. Controls whether the chair's
-- round-prompt (vote phase) auto-fires when a round caps, or only
-- fires when the user explicitly clicks an "End round & vote"
-- button in the bottom bar.
--   · 'auto'   — original behaviour: chair auto-drops round-prompt
--                at every round wrap (cap reached).
--   · 'manual' — chair never auto-drops; user must click the
--                bottom-bar button to enter vote phase.
-- Default 'auto' preserves existing behaviour for legacy rooms.
ALTER TABLE rooms ADD COLUMN vote_trigger TEXT NOT NULL DEFAULT 'auto';

"""#),
    (name: "033_room_members_removed_at.sql", sql: #"""
-- Soft-delete column on room_members so excused directors stay
-- queryable for chat-history rendering + voice replay. NULL marks
-- an active member; a non-null timestamp records when the chair
-- excused them from the room. Prior to this migration a director
-- removal hard-DELETEd the row, which dropped the director from
-- `listRoomMembers` and broke speaker-name lookups + voice profile
-- resolution for their past messages.
ALTER TABLE room_members ADD COLUMN removed_at INTEGER;

"""#),
    (name: "034_brief_viewer_variant.sql", sql: #"""
-- Persist client-picked viewer template for structured briefs (ppt /
-- magazine / newspaper). NULL = legacy deterministic pick from brief id.
ALTER TABLE briefs ADD COLUMN viewer_variant TEXT;

"""#),
    (name: "035_agent_handle_at_prefix.sql", sql: #"""
-- 035 · Agent handles · canonical form is `@slug` (was `/slug` before 2026-05).
-- Runs once on upgrade; new installs typically have seed rows already `@…`.
--
-- Rewrites each legacy `/…` handle to `@…` unless another row already owns the
-- target (UNIQUE(handle)) — in that rare case the row is left unchanged; the
-- app still resolves it via getAgentByHandle multi-candidate lookup.

UPDATE agents
SET handle = '@' || substr(agents.handle, 2)
WHERE substr(agents.handle, 1, 1) = '/'
  AND length(agents.handle) >= 2
  AND NOT EXISTS (
    SELECT 1 FROM agents AS o
    WHERE o.id != agents.id
      AND o.handle = '@' || substr(agents.handle, 2)
  );

"""#),
    (name: "036_user_topic_recs.sql", sql: #"""
-- Interest-driven topic recommendations · the home composer's
-- "找你可能感兴趣的话题" trigger drops a row in topic_rec_jobs,
-- the pipeline writes a topic_rec_batches row at start +
-- N topic_recs rows per recommendation it synthesises. The
-- composer tray pages topic_recs newest-first; each card can
-- carry web-search snippets in seed_context_json that get
-- forwarded into the room's opening message at convene time.

-- One batch per "user clicked the button" event. Lets us
-- show "generated 3h ago", keep older batches addressable via
-- pagination, and (later) attribute a room back to its rec.
CREATE TABLE topic_rec_batches (
  id            TEXT    PRIMARY KEY,
  has_web       INTEGER NOT NULL DEFAULT 0,  -- 1 = web-search ran for this batch
  keywords_json TEXT    NOT NULL,            -- JSON string[] · the 10 keywords pulled from chair memory
  created_at    INTEGER NOT NULL
);
CREATE INDEX idx_topic_rec_batches_created ON topic_rec_batches(created_at DESC);

-- One row per recommended topic. `source` drives the UI badge
-- (// web vs // memory). `seed_context_json` carries the web
-- snippets that informed this topic so the composer can attach
-- them to the room's opening message when the user convenes.
CREATE TABLE topic_recs (
  id                TEXT    PRIMARY KEY,
  batch_id          TEXT    NOT NULL REFERENCES topic_rec_batches(id) ON DELETE CASCADE,
  subject           TEXT    NOT NULL,           -- the suggested room subject
  rationale         TEXT    NOT NULL,           -- one-line "why this fits you" hint
  source            TEXT    NOT NULL,           -- 'web' | 'memory'
  seed_context_json TEXT,                       -- JSON [{ title, url, description }] · NULL when source=memory
  created_at        INTEGER NOT NULL,
  opened_room_id    TEXT    REFERENCES rooms(id) ON DELETE SET NULL
);
CREATE INDEX idx_topic_recs_created ON topic_recs(created_at DESC);
CREATE INDEX idx_topic_recs_batch   ON topic_recs(batch_id);

-- Async job tracker · 1:1 mirror of agent_persona_jobs.
-- Boot-time recovery flips status='running' → 'failed' so
-- crashed jobs surface a retry CTA instead of a hung spinner.
CREATE TABLE topic_rec_jobs (
  id            TEXT    PRIMARY KEY,
  status        TEXT    NOT NULL,                -- running | done | failed | aborted
  current_phase INTEGER NOT NULL DEFAULT 0,
  progress_pct  INTEGER NOT NULL DEFAULT 0,
  batch_id      TEXT    REFERENCES topic_rec_batches(id) ON DELETE SET NULL,
  error         TEXT,
  started_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
);
CREATE INDEX idx_topic_rec_jobs_status ON topic_rec_jobs(status);

"""#),
    (name: "037_topic_rec_tag.sql", sql: #"""
-- Per-topic category tag · the synthesiser produces a 1-2 word
-- label per recommendation (e.g. "strategy", "product", "market",
-- "ops") so the composer card can display a meaningful tag in
-- the left column instead of the source token (which was always
-- "web" / "memory" and didn't tell the user what the topic was
-- about). NULL on rows generated before this migration · the
-- frontend falls back to the source token in that case.
ALTER TABLE topic_recs ADD COLUMN tag TEXT;

"""#),
    (name: "038_message_voice.sql", sql: #"""
-- Persisted TTS audio for voice-mode messages · concatenated MP3 bytes
-- captured from live `voice-chunk` SSE stream, finalized on `voice-final`.
CREATE TABLE message_voice (
  message_id  TEXT    PRIMARY KEY,
  audio_mp3   BLOB    NOT NULL,
  meta_json   TEXT    NOT NULL,
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
);

"""#),
    (name: "039_negative_space.sql", sql: #"""
-- Negative-space memory · Layer 3.2 of the divergence stack.
-- At round-end the chair extracts "what this round did NOT touch
-- but should have" — angles raised-then-abandoned, dimensions
-- conspicuously absent. These get injected into the next round's
-- director prompts as "UNEXPLORED ANGLES" so the room has positive-
-- space breadcrumbs alongside the frame-break negative-space rules.
--
-- One row per angle (not one row per round) so the next-round
-- prompt can pull the top-N most recent regardless of round
-- boundaries · enables cross-round angle memory.
CREATE TABLE IF NOT EXISTS negative_space (
  id          TEXT PRIMARY KEY,
  room_id     TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  round_num   INTEGER NOT NULL,
  angle       TEXT NOT NULL,
  created_at  INTEGER NOT NULL,
  -- Soft consumption flag · when a subsequent round prompt injected
  -- this angle and the room actually engaged with it, the chair
  -- post-processor flips this to 1. Subsequent rounds prefer
  -- unconsumed angles to avoid suggesting the same thing twice.
  consumed    INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_negative_space_room_round
  ON negative_space(room_id, round_num);
CREATE INDEX IF NOT EXISTS idx_negative_space_room_unconsumed
  ON negative_space(room_id, consumed);

"""#),
    (name: "040_topic_branches.sql", sql: #"""
-- Topic-tree tracking · Layer 3.1 of the divergence stack.
-- Each director turn gets tagged with a branch_id · the cluster of
-- prior turns it extended. New top-level branches are surfaced when
-- a turn opens a genuinely fresh angle. Drives:
--   · dissent-gap picker (Layer 2.1) prefers directors who have NOT
--     spoken on the dominant branches
--   · UI · optional "topic map" overlay so the user sees the room's
--     coverage breadth
--   · structured summarization · long rooms can summarize by branch
--     instead of by chronological round
CREATE TABLE IF NOT EXISTS topic_branches (
  id          TEXT PRIMARY KEY,
  room_id     TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  label       TEXT NOT NULL,         -- short noun-phrase name (≤ 8 words)
  parent_id   TEXT,                  -- nullable · top-level branches have NULL
  opened_at   INTEGER NOT NULL,      -- ms epoch · ordering / decay
  -- Activity counters · maintained by the post-turn tagger so the
  -- picker can score "this branch is hot" / "this branch is unspoken".
  turn_count  INTEGER NOT NULL DEFAULT 0,
  last_speaker_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_topic_branches_room
  ON topic_branches(room_id, opened_at);

-- Per-message branch assignment · one row per director message.
-- Populated by a post-turn haiku tagger that reads the message body
-- + the room's current branch list and decides: "extends branch X"
-- or "opens new branch Y". Idempotent · re-running the tagger for
-- the same message_id replaces the row.
CREATE TABLE IF NOT EXISTS message_branches (
  message_id  TEXT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
  branch_id   TEXT NOT NULL REFERENCES topic_branches(id) ON DELETE CASCADE,
  is_opener   INTEGER NOT NULL DEFAULT 0,   -- 1 = this message opened the branch
  tagged_at   INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_message_branches_branch
  ON message_branches(branch_id);

"""#),
    (name: "041_qd_archive.sql", sql: #"""
-- Quality-Diversity behavioral archive · Layer 4 of the divergence
-- stack. Each director message gets scored on 3 behavioral
-- dimensions (abstraction-level / time-scale / stakeholder-scope) by
-- a cheap haiku post-turn. The resulting (a, t, s) triple maps to a
-- single cell in a 4×4×4 = 64-cell grid · the room's "MAP-Elites
-- archive". Picker layers can query the archive to reward
-- candidates whose persona is likely to fill an EMPTY cell, and the
-- room-end report shows coverage as a divergence KPI.
--
-- One row per (message, dimensions) so re-tagging is idempotent ·
-- the post-turn scorer always INSERT OR REPLACE.
CREATE TABLE IF NOT EXISTS qd_archive (
  message_id   TEXT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
  room_id      TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  -- Dimension scores in [0, 1] · float for diagnostics, INTEGER
  -- bucket [0, 3] for the cell index. All scored by the same haiku
  -- pass to amortize cost.
  abstraction_score  REAL NOT NULL,
  abstraction_bucket INTEGER NOT NULL,
  time_score         REAL NOT NULL,
  time_bucket        INTEGER NOT NULL,
  stakeholder_score  REAL NOT NULL,
  stakeholder_bucket INTEGER NOT NULL,
  scored_at          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_qd_archive_room
  ON qd_archive(room_id);
CREATE INDEX IF NOT EXISTS idx_qd_archive_room_cell
  ON qd_archive(room_id, abstraction_bucket, time_bucket, stakeholder_bucket);

"""#),
    (name: "042_remap_removed_models.sql", sql: #"""
-- 039_remap_removed_models.sql
--
-- Remap stored modelV strings for the six modelVs deleted from the
-- registry on 2026-05-17 (B.AI catalog reconcile + xAI removal):
--
--   opus-4-6        → opus-4-7    (Anthropic flagship peer)
--   gpt-5-5-pro     → gpt-5-5     (drop the -pro suffix; same family)
--   kimi-2-6        → kimi-k2-6   (current Kimi model · OR slug `moonshotai/kimi-k2.6`)
--   grok-4-3        → sonnet-4-6  (no Grok in registry; safe default)
--   grok-4-1-fast   → haiku-4-5   (fast-tier peer)
--   grok-4-20       → opus-4-7    (long-context peer; was 2M ctx)
--
-- Two live tables hold modelV: agents.model_v (every agent record) and
-- prefs.default_model_v (the user's default-model choice). Historical
-- snapshot tables (room_summaries.model_v, retired_token_usage.model_v,
-- usage_daily.model_v) are NOT touched — they record what actually ran
-- at the time and rewriting them would lie about history.
--
-- Idempotent · `WHERE model_v = '<old>'` is a no-op on second run.

UPDATE agents SET model_v = 'opus-4-7'   WHERE model_v = 'opus-4-6';
UPDATE agents SET model_v = 'gpt-5-5'    WHERE model_v = 'gpt-5-5-pro';
UPDATE agents SET model_v = 'kimi-k2-6'  WHERE model_v = 'kimi-2-6';
UPDATE agents SET model_v = 'sonnet-4-6' WHERE model_v = 'grok-4-3';
UPDATE agents SET model_v = 'haiku-4-5'  WHERE model_v = 'grok-4-1-fast';
UPDATE agents SET model_v = 'opus-4-7'   WHERE model_v = 'grok-4-20';

UPDATE prefs SET default_model_v = 'opus-4-7'   WHERE default_model_v = 'opus-4-6';
UPDATE prefs SET default_model_v = 'gpt-5-5'    WHERE default_model_v = 'gpt-5-5-pro';
UPDATE prefs SET default_model_v = 'kimi-k2-6'  WHERE default_model_v = 'kimi-2-6';
UPDATE prefs SET default_model_v = 'sonnet-4-6' WHERE default_model_v = 'grok-4-3';
UPDATE prefs SET default_model_v = 'haiku-4-5'  WHERE default_model_v = 'grok-4-1-fast';
UPDATE prefs SET default_model_v = 'opus-4-7'   WHERE default_model_v = 'grok-4-20';

"""#),
    (name: "043_remap_kimi_k2_5_to_k2_6.sql", sql: #"""
-- 040_remap_kimi_k2_5_to_k2_6.sql
--
-- Bump stored `kimi-k2-5` rows to `kimi-k2-6` after the Kimi registry
-- entry was renamed (OpenRouter exposes the slug as
-- `moonshotai/kimi-k2.6`; the prior `moonshotai/kimi-k2.5` slug 404s).
--
-- This complements 039_remap_removed_models.sql: 039 was edited to
-- land users directly on `kimi-k2-6` for first-time runs, but any DB
-- that already ran the previous 039 (which mapped to `kimi-k2-5`) is
-- left holding the now-unknown `kimi-k2-5` string. This migration
-- fixes those. Idempotent · WHERE clause is a no-op on second run.
--
-- Live tables only (`agents.model_v`, `prefs.default_model_v`).
-- Historical snapshot tables are not touched — they record what
-- actually ran at the time.

UPDATE agents SET model_v = 'kimi-k2-6'  WHERE model_v = 'kimi-k2-5';
UPDATE prefs  SET default_model_v = 'kimi-k2-6'  WHERE default_model_v = 'kimi-k2-5';

"""#),
    (name: "044_one_active_llm_key.sql", sql: #"""
-- 041_one_active_llm_key.sql
--
-- ⚠️ DEPRECATED · superseded by 042_active_llm_provider_pref.sql
--
-- This migration originally collapsed multi-key LLM configurations
-- down to one row by deleting all but the highest-priority. The
-- design moved on: under the "multi-SIM" model (see migration 042)
-- users keep MULTIPLE LLM provider keys on file, with a single
-- `prefs.active_llm_provider` field flagging which one is currently
-- routed through. Destructive deletion was the wrong tool — users
-- want to switch between configured providers without re-pasting.
--
-- This file is kept as a no-op so the MIGRATIONS array indices stay
-- stable and so any installation that already recorded "041 applied"
-- (the developer who first ran the destructive version on a local
-- db) doesn't try to re-run anything. SQLite's _migrations table is
-- keyed by name, not content; the recorded run blocks future
-- executions regardless of what the SQL says here.
--
-- New installs of v0.1.25+ see the no-op below, so users upgrading
-- with multiple LLM keys configured under v0.1.24 don't lose data.

SELECT 1;

"""#),
    (name: "045_active_llm_provider_pref.sql", sql: #"""
-- 042_active_llm_provider_pref.sql
--
-- Multi-SIM LLM provider model · users keep multiple LLM keys on file
-- and flag exactly one as the active routing carrier. This column
-- replaces the destructive-collapse approach 041 attempted; key rows
-- are preserved, the user switches by changing this pref value.
--
-- Seed value · the highest-priority LLM key currently configured at
-- migration time (matches the ordering used by `LLM_PROVIDER_PRIORITY`
-- in `src/ai/providers.ts`). NULL when no LLM key exists. The runtime
-- still derives `defaultModelV` from this carrier; reconcile sweeps
-- agents accordingly.
--
-- Future addition of LLM providers: this migration's seed is one-shot
-- and only matters for existing users. New installs hit the empty
-- column and walk through onboarding to set their first provider as
-- active.

ALTER TABLE prefs ADD COLUMN active_llm_provider TEXT;

-- Seed from existing key set · pick the highest-priority configured
-- LLM provider (openrouter > bai > anthropic > openai > google > xai).
-- The seed is a one-shot UPDATE that only matches rows where the new
-- column is still NULL (= every existing prefs row).
UPDATE prefs
   SET active_llm_provider = (
     SELECT provider
       FROM provider_keys
      WHERE provider IN ('openrouter','bai','anthropic','openai','google','xai')
        AND length(key_blob) > 0
      ORDER BY CASE provider
                 WHEN 'openrouter' THEN 1
                 WHEN 'bai'        THEN 2
                 WHEN 'anthropic'  THEN 3
                 WHEN 'openai'     THEN 4
                 WHEN 'google'     THEN 5
                 WHEN 'xai'        THEN 6
               END
      LIMIT 1
   )
 WHERE active_llm_provider IS NULL;

"""#),
    (name: "046_llm_credentials.sql", sql: #"""
-- 043_llm_credentials.sql
--
-- Multi-instance LLM provider credentials · the same provider can now
-- be added more than once (e.g. two separate OpenRouter accounts, or
-- a personal + team B.AI key). The legacy `provider_keys` table is
-- keyed by `provider` (one row per provider), which doesn't support
-- this. We introduce a new table keyed by an opaque `id` so the same
-- provider can appear multiple times with distinct user-supplied
-- labels.
--
-- Voice (minimax, elevenlabs) and skill (brave, tavily) keys stay in
-- `provider_keys` — they have no use case for multiple credentials
-- per provider and the existing routes work fine for them.
--
-- `prefs.active_llm_credential_id` replaces the brief-lived
-- `prefs.active_llm_provider` from migration 042. Switching is now a
-- one-write change to this id; the old column stays in place (NULL
-- after this migration) to avoid an ALTER…DROP COLUMN that requires
-- table rebuilds on older SQLite.

CREATE TABLE IF NOT EXISTS llm_credentials (
  id          TEXT PRIMARY KEY,
  provider    TEXT NOT NULL,
  label       TEXT NOT NULL,
  key_blob    BLOB NOT NULL,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS llm_credentials_provider_idx
  ON llm_credentials(provider);

ALTER TABLE prefs ADD COLUMN active_llm_credential_id TEXT;

-- One-shot migration · for every configured LLM row in provider_keys,
-- create a credential row carrying the same encrypted key_blob. The
-- generated id uses a 12-char base64 slice of randomblob() for
-- collision-resistance; labels default to the provider's display
-- name (frontend will surface them under that label until the user
-- renames). Empty key_blobs are skipped (legacy "ever-configured"
-- rows that have since been emptied).
INSERT INTO llm_credentials (id, provider, label, key_blob, created_at, updated_at)
SELECT
  lower(hex(randomblob(8))) AS id,
  provider,
  CASE provider
    WHEN 'openrouter' THEN 'OpenRouter'
    WHEN 'bai'        THEN 'B.AI'
    WHEN 'anthropic'  THEN 'Claude'
    WHEN 'openai'     THEN 'ChatGPT'
    WHEN 'google'     THEN 'Gemini'
    WHEN 'xai'        THEN 'Grok'
    WHEN 'deepseek'   THEN 'DeepSeek'
    ELSE provider
  END AS label,
  key_blob,
  created_at,
  updated_at
FROM provider_keys
WHERE provider IN ('openrouter','bai','anthropic','openai','google','xai','deepseek')
  AND length(key_blob) > 0;

-- Seed prefs.active_llm_credential_id with the highest-priority
-- migrated credential. Priority mirrors LLM_PROVIDER_PRIORITY in
-- src/ai/providers.ts.
UPDATE prefs
   SET active_llm_credential_id = (
     SELECT id FROM llm_credentials
      ORDER BY CASE provider
                 WHEN 'openrouter' THEN 1
                 WHEN 'bai'        THEN 2
                 WHEN 'anthropic'  THEN 3
                 WHEN 'openai'     THEN 4
                 WHEN 'google'     THEN 5
                 WHEN 'xai'        THEN 6
                 WHEN 'deepseek'   THEN 7
               END,
               created_at ASC
      LIMIT 1
   )
 WHERE id = 1
   AND active_llm_credential_id IS NULL;

-- Clear the now-redundant active_llm_provider · the credential id is
-- the new source of truth. The column stays in the schema (avoids a
-- table rebuild) but post-migration it's always NULL; any reader
-- that still consults it sees "no active" and falls back to the
-- credential lookup.
UPDATE prefs SET active_llm_provider = NULL WHERE id = 1;

-- Finally · remove the migrated LLM rows from provider_keys so the
-- table is purely voice + skill from here on. Cleared by name; an
-- explicit IN() list matches what we inserted above.
DELETE FROM provider_keys
 WHERE provider IN ('openrouter','bai','anthropic','openai','google','xai','deepseek');

"""#),
    (name: "047_drop_topic_recs.sql", sql: #"""
-- 044_drop_topic_recs.sql
--
-- The interest-driven topic-recommendations feature ("找你可能感
-- 兴趣的话题" trigger card + the recommendation cards under the
-- home composer) has been removed. Its replacement is a static
-- catalog of five scenario ad cards rendered purely on the
-- frontend (see public/app.js · SCENARIO_CARDS), so there is no
-- need to keep the storage tables that fed the old dynamic tray.
--
-- Tables (and their indexes) removed:
--   · topic_rec_jobs        · async generation job tracking
--   · topic_recs            · synthesised recommendation rows
--   · topic_rec_batches     · one row per generation run
--
-- Drop order matters: topic_recs / topic_rec_jobs both FK into
-- topic_rec_batches (ON DELETE CASCADE / SET NULL), so SQLite
-- needs the child tables removed first when foreign_keys is ON.
-- `DROP TABLE IF EXISTS` is idempotent — re-runs are a no-op.

DROP TABLE IF EXISTS topic_recs;
DROP TABLE IF EXISTS topic_rec_jobs;
DROP TABLE IF EXISTS topic_rec_batches;

"""#),
    (name: "048_user_long_memory.sql", sql: #"""
-- 048_user_long_memory.sql
--
-- Long-term USER memory sanctuary · a parallel lane that the
-- auto-dream cycle never touches. The chair's existing memory
-- consolidation (heuristic decay → cluster → merge → conflict
-- → promote-to-long, in src/orchestrator/dream.ts) strips
-- abstract recurring facts about the user along with the noise.
-- This table holds tag-shaped abstractions ("founder",
-- "anti-jargon", "long-horizon-bias") that survive forever and
-- are only displaced on explicit contradiction.
--
-- Per the project design doc: rows here are owned conceptually
-- by the chair-relationship (the chair is the user's interface
-- to the boardroom). There is one user per install, so no
-- user_id column. No agent_id either — facts here are about
-- the USER, not authored by any single director.
--
-- Lifecycle:
--   · Insert · the dream pipeline's new Step 6 (chair-only)
--              harvests durable patterns from chair's tier='long'
--              memories and writes them here.
--   · Reinforce · same harvest step bumps provenance_rooms +
--                 last_reinforced_at when an existing tag is
--                 confirmed by new evidence.
--   · Supersede · only on direct contradiction · sets
--                 superseded_by on the older row and inserts a
--                 new row. The old row stays for audit.
--   · Delete · only via the user's explicit UI action on the
--              chair's profile page, OR the cap-30 safety prune.
--
-- The dream cycle's pruning of unused agent_memories continues
-- unchanged — this table is purely additive and sits outside
-- that lifecycle.

CREATE TABLE user_long_memory (
  id                  TEXT    PRIMARY KEY,
  label               TEXT    NOT NULL,                -- ≤ 32 chars · short tag
  claim               TEXT    NOT NULL,                -- ≤ 240 chars · unpacked sentence
  confidence          REAL    NOT NULL DEFAULT 0.7,    -- 0..1
  provenance_rooms    INTEGER NOT NULL DEFAULT 1,      -- distinct rooms reinforcing it
  last_reinforced_at  INTEGER,                         -- ms epoch · last harvest re-counting this tag
  superseded_by       TEXT    REFERENCES user_long_memory(id) ON DELETE SET NULL,
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL
);

-- Active rows query · `WHERE superseded_by IS NULL ORDER BY
-- provenance_rooms DESC, last_reinforced_at DESC` is the hot
-- path (chair prompt + chair-profile UI both call it). The
-- index includes superseded_by as the leading column so the
-- IS NULL filter is index-resolvable.
CREATE INDEX idx_user_long_memory_active
  ON user_long_memory(superseded_by, provenance_rooms DESC, last_reinforced_at DESC);

"""#),
    (name: "049_voice_credentials.sql", sql: #"""
-- 049_voice_credentials.sql
--
-- Multi-instance VOICE TTS provider credentials · mirrors the LLM
-- credential model that landed in 046. The same TTS provider can
-- now be added more than once (e.g. two MiniMax accounts, or
-- personal + team ElevenLabs) with distinct user-supplied labels.
-- Legacy `provider_keys` was keyed by `provider` (one row per
-- provider), which doesn't support this. The new table is keyed by
-- an opaque `id`.
--
-- `prefs.active_voice_credential_id` is the single pointer that
-- decides which TTS provider is "active" right now. Switching is
-- a one-write change to this id; the credential rows themselves
-- stay on file so the user can flip back without re-pasting.
--
-- Skill keys (brave, tavily) remain in `provider_keys` — they have
-- no use case for multiple credentials per provider and their
-- routes work fine as-is. After this migration, `provider_keys`
-- holds ONLY skill rows.

CREATE TABLE IF NOT EXISTS voice_credentials (
  id          TEXT PRIMARY KEY,
  provider    TEXT NOT NULL,
  label       TEXT NOT NULL,
  key_blob    BLOB NOT NULL,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS voice_credentials_provider_idx
  ON voice_credentials(provider);

ALTER TABLE prefs ADD COLUMN active_voice_credential_id TEXT;

-- One-shot migration · move every configured voice row from
-- provider_keys into voice_credentials. Generated id uses a
-- 16-char hex randomblob slice for collision resistance; labels
-- default to the provider's display name (UI surfaces them under
-- that label until the user renames). Empty key_blobs are skipped
-- (legacy "ever-configured" rows that have since been emptied).
INSERT INTO voice_credentials (id, provider, label, key_blob, created_at, updated_at)
SELECT
  lower(hex(randomblob(8))) AS id,
  provider,
  CASE provider
    WHEN 'minimax'    THEN 'MiniMax'
    WHEN 'elevenlabs' THEN 'ElevenLabs'
    ELSE provider
  END AS label,
  key_blob,
  created_at,
  updated_at
FROM provider_keys
WHERE provider IN ('minimax','elevenlabs')
  AND length(key_blob) > 0;

-- Seed prefs.active_voice_credential_id with the highest-priority
-- migrated credential. Priority mirrors the existing fallback chain
-- in src/voice/tts.ts:165-179 (MiniMax > ElevenLabs).
UPDATE prefs
   SET active_voice_credential_id = (
     SELECT id FROM voice_credentials
      ORDER BY CASE provider
                 WHEN 'minimax'    THEN 1
                 WHEN 'elevenlabs' THEN 2
               END,
               created_at ASC
      LIMIT 1
   )
 WHERE id = 1
   AND active_voice_credential_id IS NULL;

-- Finally · remove the migrated voice rows from provider_keys so
-- that table is purely skill keys (brave + tavily) from here on.
-- Cleared by name; an explicit IN() list matches what we inserted
-- above. After this migration, `getKey("minimax")` and
-- `getKey("elevenlabs")` always return null; callers must read
-- the active voice credential instead.
DELETE FROM provider_keys
 WHERE provider IN ('minimax','elevenlabs');

"""#),
    (name: "050_agent_provider_buckets.sql", sql: #"""
-- 050_agent_provider_buckets.sql
--
-- SIM-swap memory for per-agent model + voice picks · keyed by
-- provider. Today every `agents` row stores a single `model_v` and a
-- single `voice_json`; switching the active LLM credential's provider
-- runs `reconcileAgentModels({forcePrimary:true})` which overwrites
-- both fields with random picks from the new carrier's pool · the
-- user's manual per-director picks under the prior provider are lost.
--
-- This migration adds two TEXT columns that hold a JSON map keyed by
-- provider (LLM carrier for `model_by_provider_json`, voice provider
-- for `voice_by_provider_json`). The reconcile pass now:
--   1. Phase 1 · snapshots the current `model_v` / `voice_json` into
--      `bucket[priorProvider]` BEFORE overwriting.
--   2. Phase 2 · reads `bucket[newProvider]` and restores from it if
--      present (reachability-checked for models). Falls back to the
--      existing random-fast-pool pick when the bucket is empty / stale.
--
-- Effect · switching provider feels like a SIM swap. Every per-agent
-- config that existed on a provider is preserved and restored on the
-- next visit to that provider.
--
-- Purely additive · both columns start NULL on every existing row.
-- No data migration step; buckets seed organically as the user picks
-- models / switches providers post-deploy. The migration runner's
-- "already-applied" guard at db.ts handles ALTER retries idempotently
-- if a rebase ever reorders this past a column it adds elsewhere.

ALTER TABLE agents ADD COLUMN model_by_provider_json TEXT;
ALTER TABLE agents ADD COLUMN voice_by_provider_json TEXT;

"""#),
    (name: "051_search_credentials.sql", sql: #"""
-- 051_search_credentials.sql
--
-- Multi-instance SEARCH provider credentials · final mirror of the
-- pattern that migrations 044-046 introduced for LLM and migration 049
-- introduced for Voice TTS. The same web-search provider (Brave or
-- Tavily) can now appear multiple times with distinct user-supplied
-- labels (personal + team account, for example), with exactly one
-- "active" credential pointed to by `prefs.active_search_credential_id`.
--
-- After this migration runs, `provider_keys` is EMPTY · every
-- credential the user holds (LLM / voice / search) lives in its own
-- typed table with `(id, provider, label, key_blob)` columns. The
-- legacy `provider_keys` table itself stays in the schema for now ·
-- it's structurally tiny and dropping it would require coordinated
-- removal of the `getKey` / `setKey` helpers in `keys.ts`, which is
-- noise unrelated to this feature.
--
-- Unlike the LLM and voice flips, switching active search provider
-- has NO per-agent reshuffle · agents don't carry per-search-provider
-- state, so the active swap is purely a routing decision that the
-- next web-search call honours automatically. No `reconcile-*`
-- helper is needed.

CREATE TABLE IF NOT EXISTS search_credentials (
  id          TEXT PRIMARY KEY,
  provider    TEXT NOT NULL,                -- 'brave' | 'tavily'
  label       TEXT NOT NULL,
  key_blob    BLOB NOT NULL,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS search_credentials_provider_idx
  ON search_credentials(provider);

ALTER TABLE prefs ADD COLUMN active_search_credential_id TEXT;

-- One-shot migration · move every configured brave/tavily row from
-- provider_keys into search_credentials. Labels default to the
-- provider's display name; the seed-active step below picks brave
-- when both exist (matches the historical `webSearchProvider` default
-- of "brave" set in migration 029).
INSERT INTO search_credentials (id, provider, label, key_blob, created_at, updated_at)
SELECT
  lower(hex(randomblob(8))) AS id,
  provider,
  CASE provider
    WHEN 'brave'  THEN 'Brave Search'
    WHEN 'tavily' THEN 'Tavily Search'
    ELSE provider
  END AS label,
  key_blob,
  created_at,
  updated_at
FROM provider_keys
WHERE provider IN ('brave','tavily')
  AND length(key_blob) > 0;

-- Seed prefs.active_search_credential_id with the highest-priority
-- migrated credential. Priority mirrors the historical default in
-- migration 029 (brave first, tavily as alternate). If the user had
-- previously expressed a `web_search_provider = 'tavily'` preference,
-- that's preserved here by sorting on that pref first.
UPDATE prefs
   SET active_search_credential_id = (
     SELECT id FROM search_credentials
      ORDER BY CASE provider
                 WHEN (SELECT COALESCE(web_search_provider, 'brave') FROM prefs WHERE id = 1) THEN 0
                 WHEN 'brave'  THEN 1
                 WHEN 'tavily' THEN 2
               END,
               created_at ASC
      LIMIT 1
   )
 WHERE id = 1
   AND active_search_credential_id IS NULL;

-- Finally · remove the migrated search rows from provider_keys so
-- the legacy table is fully drained (all four credentialed providers
-- · openai/anthropic/google/xai for LLM, minimax/elevenlabs for voice,
-- brave/tavily for search · now live in their typed tables). After
-- this migration, `getKey("brave")` and `getKey("tavily")` always
-- return null · callers must read the active search credential via
-- `getActiveSearchKeyPlaintext()` instead.
DELETE FROM provider_keys
 WHERE provider IN ('brave','tavily');

"""#),
    (name: "052_room_name_auto.sql", sql: #"""
-- 052_room_name_auto.sql
-- Track whether a room's `name` was auto-derived from the opening
-- question's first 60 chars (default · 1) or explicitly set by the
-- client at creation (0). The orchestrator's round-1-complete hook
-- runs an LLM topic-phrase summariser and writes a short title back
-- ONLY when name_auto = 1 (SQL-side guard via UPDATE WHERE), so any
-- future rename UI can flip the flag to 0 without racing the auto
-- pipeline.

ALTER TABLE rooms ADD COLUMN name_auto INTEGER NOT NULL DEFAULT 1;

"""#),
    (name: "053_room_threads.sql", sql: #"""
-- 053_room_threads.sql · Private 1:1 threads with a single director.
--
-- A "thread" is a lightweight room spawned from a live room (the
-- parent) for the user to pull one director aside without exposing
-- the conversation to the other directors. The thread reuses the
-- regular `rooms` / `messages` / `room_members` plumbing — only two
-- discriminators tell it apart:
--
--   room_kind            · 'main' (default · all existing rows) or 'thread'
--   thread_director_id   · the single director the thread is with;
--                          NULL on main rooms
--
-- parent_room_id (added in 020) is reused to point at the parent
-- main room. The follow-up-room feature also uses parent_room_id,
-- so callers must disambiguate via room_kind (follow-up = 'main'
-- with parent_room_id set; thread = 'thread' with both set).
--
-- No FK constraints — main room deletion handled at storage layer
-- so a future hard-delete path can cascade thread rooms explicitly.

ALTER TABLE rooms ADD COLUMN room_kind          TEXT NOT NULL DEFAULT 'main';
ALTER TABLE rooms ADD COLUMN thread_director_id TEXT NULL;

-- Index the parent → child relationship for the common dock-bar /
-- "list threads in this room" query. Filter to threads only so the
-- much larger main-room population doesn't dominate the index.
CREATE INDEX IF NOT EXISTS idx_rooms_parent_thread
  ON rooms (parent_room_id, room_kind)
  WHERE room_kind = 'thread';

"""#),
    (name: "054_voice_clone_jobs.sql", sql: #"""
-- 054_voice_clone_jobs.sql · Persist voice-clone jobs across a process restart.
--
-- A clone job spans 5-60 s (YouTube fetch → upload → clone) and the
-- user can minimize the modal into a bottom-right pill. If the
-- process is killed mid-job (Ctrl+C, hard restart) the row would
-- otherwise be left in `running` forever; boot-time recovery (see
-- src/boot.ts) flips stale `running` rows to `failed` so the UI can
-- surface "last clone was interrupted" instead of silently losing it.
--
-- Fields:
--   id            uuid · primary key, also exposed to client as jobId
--   agent_id      director receiving the cloned voice
--   provider      'minimax' | 'elevenlabs' · resolved from active credential at start
--   source_kind   'file' | 'youtube'
--   source_ref    absolute filesystem path (file) or YouTube URL (youtube)
--   label         user-supplied display label for the new voice; nullable
--   status        'queued' | 'running' | 'done' | 'failed' | 'cancelled'
--   current_stage 'fetch' | 'upload' | 'clone' · which 3rd of the pipeline
--   pct           0-100 overall progress (each stage covers ~33 pp)
--   voice_id      provider-issued voice id when status='done'; NULL otherwise
--   error_code    short token like 'yt_age_gated' / 'provider_quota'
--   error_message human-readable detail for the modal
--   created_at    epoch millis
--   updated_at    epoch millis · refreshed on every progress write

CREATE TABLE IF NOT EXISTS clone_jobs (
  id            TEXT PRIMARY KEY,
  agent_id      TEXT NOT NULL,
  provider      TEXT NOT NULL,
  source_kind   TEXT NOT NULL,
  source_ref    TEXT NOT NULL,
  label         TEXT,
  status        TEXT NOT NULL DEFAULT 'queued',
  current_stage TEXT NOT NULL DEFAULT 'fetch',
  pct           INTEGER NOT NULL DEFAULT 0,
  voice_id      TEXT,
  error_code    TEXT,
  error_message TEXT,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_clone_jobs_status_updated
  ON clone_jobs (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_clone_jobs_agent_running
  ON clone_jobs (agent_id, status)
  WHERE status IN ('queued', 'running');

"""#),
    (name: "055_voice_labels.sql", sql: #"""
-- 055_voice_labels.sql · Persist user-supplied friendly names for
-- provider voice_ids that don't have a name field of their own.
--
-- MiniMax's `voice_clone` API has no `name` parameter — the voice_id
-- IS the dashboard label — so when the user typed "Chloe" in the
-- clone modal, that string never reaches MiniMax. Previously we
-- mirrored the label to localStorage, which dies the moment the
-- user clears site data or moves to another machine. This table is
-- the durable record. `listVoicesPage` merges it into the catalogue
-- response so the picker / trigger / message-author labels stay
-- friendly across reloads, devices, and DB exports.
--
-- Fields:
--   voice_id    TEXT PRIMARY KEY · provider-issued voice id
--   provider    TEXT NOT NULL    · 'minimax' | 'elevenlabs'
--   label       TEXT NOT NULL    · user-typed name from the clone modal
--   created_at  INTEGER NOT NULL · epoch ms
--   updated_at  INTEGER NOT NULL · epoch ms · refreshed on rename

CREATE TABLE IF NOT EXISTS voice_labels (
  voice_id   TEXT PRIMARY KEY,
  provider   TEXT NOT NULL,
  label      TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS voice_labels_provider_idx
  ON voice_labels(provider);

"""#),
    (name: "056_agent_user_rules.sql", sql: #"""
-- 056_agent_user_rules.sql · Persist the per-director "rules" the user
-- types in the agent profile.
--
-- These rules were previously stored only in the browser's localStorage
-- (`boardroom.agent.rules.<slug>`) and never reached the server — so the
-- orchestrator never injected them into the director's turn prompt and
-- the model silently ignored them (e.g. "never mention 范冰冰" had zero
-- effect). This column makes them durable + server-side so the prompt
-- builder can inject them as hard constraints.
--
-- Stored as a JSON array of strings, e.g. ["不要谈及范冰冰", "always cite a number"].
-- NULL / absent means "no user rules" (the common case).
ALTER TABLE agents ADD COLUMN user_rules_json TEXT;

"""#),
    (name: "057_agent_avatar3d.sql", sql: #"""
-- 057_agent_avatar3d.sql · Persist the per-director 3D-avatar config the user
-- builds in the "捏 avatar" editor (the rigged-GLB customizer).
--
-- The config selects a body style + independent hair / clothing / accessory
-- dimensions and skin / hair / brow / outfit colours. It is stored as a JSON
-- object, e.g.
--   {"model":"casual","hairStyle":"glasses","outfitStyle":"casual",
--    "accessory":"headphones","skin":"#f1c27d","hair":"#241c16",
--    "brow":"#241c16","outfit":"#3b5b78"}
--
-- Needed server-side so (a) the editor reopens with the saved look and (b) the
-- voice room can rebuild each director's 3D figure from it. NULL / absent means
-- "no saved config" → the room falls back to a deterministic per-id default.
-- (The rendered PNG screenshot is stored separately in the existing avatar_path
-- column, reusing the 2D avatar display pipeline.)
ALTER TABLE agents ADD COLUMN avatar3d_json TEXT;

"""#),
    (name: "058_prefs_avatar3d.sql", sql: #"""
-- 058_prefs_avatar3d.sql · Let the USER (host) have a 3D "捏 avatar" too,
-- mirroring the per-director avatar3d feature (migration 057).
--
-- avatar3d_json · the customizer config { model, hairStyle, outfitStyle,
--   accessory, skin, hair, brow, outfit } so the editor reopens with the
--   saved look. NULL → the user has no 3D avatar (falls back to the 8-bit
--   seed-generated SVG in avatar_seed).
-- avatar_url · the rendered PNG portrait (data URL). Unlike directors, the
--   user's 2D avatar was previously generated on the fly from avatar_seed
--   (no stored image), so we need a column to hold the 3D screenshot that
--   the sidebar / room / settings then display in preference to the SVG.
ALTER TABLE prefs ADD COLUMN avatar3d_json TEXT;
ALTER TABLE prefs ADD COLUMN avatar_url TEXT;

"""#),
    ]
}
