/**
 * Hierarchical room summarization · keeps long rooms under context-window
 * pressure without losing thread continuity. Three tiers:
 *
 *   L0 (verbatim) · last L0_KEEP rounds · loaded straight from messages
 *   L1 (per-round) · rounds in [current - L1_BACK, current - L0_KEEP] ·
 *                    one cached summary per round, generated by a
 *                    cheap utility model the moment the round drops
 *                    out of L0
 *   L2 (rolling)  · everything older than L1 · single consolidated row,
 *                   regenerated whenever a new L1 row gets folded in
 *
 * Always-anchored (no compression at any age):
 *   · room.subject (the original question)
 *   · all user messages (load-bearing pivots, cheap to keep)
 *   · chair convening messages (the cast intro, foundational)
 *
 * Trigger · runRoundEndSummarization(roomId, roundJustEnded) is called
 * by chair.runChairRoundEnd after key-points are persisted. From round
 * (L0_KEEP + 1) onward each round-end fires one L1 generation; from
 * round (L1_BACK + 1) onward each round-end ALSO regenerates L2.
 *
 * Both LLM calls go through utilityModelFor(), which routes per the
 * user's configured carrier (openrouter→haiku, openai→gpt-mini,
 * google→gemini-flash, xai→grok-fast). No frontier-model burn.
 */
import { utilityModelFor } from "../ai/availability.js";
import { callLLM } from "../ai/adapter.js";
import type { ModelV } from "../ai/registry.js";
import { getAgent } from "../storage/agents.js";
import { listMessages, type Message } from "../storage/messages.js";
import { getPrefs } from "../storage/prefs.js";
import {
  deleteL1Summary,
  getL1Summary,
  getL2Summary,
  upsertL1Summary,
  upsertL2Summary,
} from "../storage/summaries.js";
import { listKeyPointsForRoom } from "../storage/key_points.js";

/** Tier thresholds · expressed in rounds. */
export const L0_KEEP = 5;        // last N rounds kept verbatim
export const L1_BACK = 10;       // rounds [current - L1_BACK, current - L0_KEEP] held as L1

/** Soft token cap for the assembled history segment of a director's
 *  context (system prompt sections + history). Beyond this, the
 *  context assembler in context.ts trims aggressively (drops oldest
 *  L0 messages first; the summaries are already compact). 16k chosen
 *  to give frontier models with 200k+ windows headroom for the
 *  director's own reasoning trace + per-turn scaffolding without
 *  inviting context-rot from a stuffed prompt. */
export const HISTORY_TOKEN_CAP = 16_000;

/**
 * Run after each round-end (post key-point extraction). Decides which
 * L1 / L2 summaries need (re)generation and produces them. Failure is
 * non-fatal · summarisation is best-effort, the room still advances.
 */
export async function runRoundEndSummarization(
  roomId: string,
  roundJustEnded: number,
): Promise<void> {
  // Round R just ended. The round that newly drops out of L0 is
  // R - L0_KEEP + 1. (Example with L0_KEEP=5: when round 6 ends, the
  // L0 window covers 2..6, so round 1 is newly demoted.)
  const l1Target = roundJustEnded - L0_KEEP + 1;
  if (l1Target < 1) return;

  if (!getL1Summary(roomId, l1Target)) {
    try {
      await generateL1ForRound(roomId, l1Target);
    } catch (e) {
      process.stderr.write(
        `[summarize] L1 round ${l1Target} room=${roomId} failed: ${e instanceof Error ? e.message : String(e)}\n`,
      );
    }
  }

  // Whenever a round gets demoted from the L1 window into L2 (newly
  // older than L1_BACK), fold its L1 row into a regenerated L2 row.
  const l2Target = roundJustEnded - L1_BACK + 1;
  if (l2Target < 1) return;

  const l1ForFolding = getL1Summary(roomId, l2Target);
  if (l1ForFolding) {
    try {
      await foldL1IntoL2(roomId, l1ForFolding.roundNum!, l1ForFolding.body);
      deleteL1Summary(roomId, l1ForFolding.roundNum!);
    } catch (e) {
      process.stderr.write(
        `[summarize] L2 fold round ${l2Target} room=${roomId} failed: ${e instanceof Error ? e.message : String(e)}\n`,
      );
    }
  }
}

/** Build an L1 narrative for a single round and persist it. */
async function generateL1ForRound(roomId: string, roundNum: number): Promise<void> {
  const all = listMessages(roomId);
  const inRound = all.filter((m) => m.roundNum === roundNum);
  if (inRound.length === 0) return;

  const transcript = renderTranscript(inRound);
  if (!transcript.trim()) return;

  // Pull this round's chair-extracted key points (if any) — they're a
  // useful anchor for the model · "these are the points the chair
  // judged worth surfacing; preserve them in the narrative."
  const keyPoints = listKeyPointsForRoom(roomId).filter((kp) => kp.roundNum === roundNum);
  const keyPointsBlock = keyPoints.length
    ? "\n\nChair's key points from this round:\n" +
      keyPoints.map((kp, i) => `${i + 1}. ${kp.body}`).join("\n")
    : "";

  const modelV = utilityModelFor();
  if (!modelV) return; // no carrier configured · skip silently

  const prompt =
    `Summarise round ${roundNum} of a multi-director boardroom discussion in 2-4 short sentences. ` +
    `Capture: (a) what the directors actually said (their distinct positions, not just topics), ` +
    `(b) where they pushed back on each other, (c) any concrete claim or recommendation that emerged. ` +
    `Do NOT restate the original question. Do NOT add commentary. Plain prose, third person, present tense.` +
    `\n\n--- Round ${roundNum} transcript ---\n${transcript}` +
    keyPointsBlock;

  const body = await callLLM({
    modelV: modelV as ModelV,
    carrier: null,
    messages: [
      { role: "user", content: prompt },
    ],
    temperature: 0.2,
    maxTokens: 400,
  });
  const trimmed = body.trim();
  if (!trimmed) return;

  upsertL1Summary({
    roomId,
    roundNum,
    body: trimmed,
    modelV,
    sourceHash: hashOf(transcript + keyPointsBlock),
  });
}

/**
 * Combine the existing L2 (if any) with the freshly-demoted L1 chunk
 * and ask the cheap model to produce a single tight narrative covering
 * everything older than the L1 window.
 */
async function foldL1IntoL2(
  roomId: string,
  newRoundNum: number,
  newL1Body: string,
): Promise<void> {
  const existing = getL2Summary(roomId);
  const startRound = existing?.startRound ?? newRoundNum;
  const endRound = newRoundNum;

  const modelV = utilityModelFor();
  if (!modelV) return;

  const previousBlock = existing?.body
    ? `Previous narrative covering rounds ${existing.startRound}-${existing.endRound}:\n${existing.body}\n\n`
    : "";

  const prompt =
    `You maintain a rolling consolidated narrative of an ongoing multi-director boardroom discussion. ` +
    `A new round just dropped out of the recent window and needs to be folded in. ` +
    `Produce a single narrative of 4-7 sentences covering rounds ${startRound} through ${endRound}. ` +
    `Preserve: each director's evolving position, where the discussion sharpened, decisions / commitments that emerged. ` +
    `Drop: minor exchanges, repeated points already captured. Plain prose, third person.` +
    `\n\n${previousBlock}` +
    `New round ${newRoundNum} (just demoted from L1):\n${newL1Body}`;

  const body = await callLLM({
    modelV: modelV as ModelV,
    carrier: null,
    messages: [{ role: "user", content: prompt }],
    temperature: 0.25,
    maxTokens: 600,
  });
  const trimmed = body.trim();
  if (!trimmed) return;

  upsertL2Summary({
    roomId,
    startRound,
    endRound,
    body: trimmed,
    modelV,
    sourceHash: hashOf((existing?.body ?? "") + newL1Body),
  });
}

/** Render a chunk of messages as a readable transcript for the
 *  summarizer. Skips system messages and chair settings/round-prompt
 *  noise — only the substance of what was said this round. */
function renderTranscript(messages: Message[]): string {
  const prefs = getPrefs();
  const lines: string[] = [];
  for (const m of messages) {
    if (m.authorKind === "system") continue;
    if (m.authorKind === "agent") {
      const meta = (m.meta || {}) as { kind?: string };
      // Skip pure procedural chair messages — they're round-open
      // markers, settings notices, etc., not substance.
      if (meta.kind === "round-open" || meta.kind === "settings" || meta.kind === "round-prompt") continue;
      const a = m.authorId ? getAgent(m.authorId) : null;
      const name = a ? a.name : "Director";
      lines.push(`${name}: ${m.body.trim()}`);
    } else if (m.authorKind === "user") {
      lines.push(`${prefs.name || "User"}: ${m.body.trim()}`);
    }
  }
  return lines.join("\n\n");
}

/** Tiny non-crypto hash for source-fingerprinting. */
function hashOf(s: string): string {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(16);
}
