import Foundation
import SwiftUI

/// Lightweight i18n · mirrors the web `t(key, params)` (i18n-mobile.js): looks
/// up the current locale, falls back to English, then to the key itself.
/// Interpolation uses `{name}` placeholders. Locale persists in UserDefaults.
/// Strings are ported from i18n-mobile.js (EN complete for shipped screens; ZH
/// for the same; JA/ES fall back to EN until ported).
enum Loc {
    static let supported = ["en", "zh", "ja", "es"]
    static let localeNames = ["en": "English", "zh": "简体中文", "ja": "日本語", "es": "Español"]

    private static let key = "boardroom.uiLocale"

    static var locale: String = {
        if let saved = UserDefaults.standard.string(forKey: key), supported.contains(saved) { return saved }
        let dev = String(Locale.preferredLanguages.first?.prefix(2) ?? "en")
        return supported.contains(dev) ? dev : "en"
    }()

    static func setLocale(_ l: String) {
        guard supported.contains(l) else { return }
        locale = l
        UserDefaults.standard.set(l, forKey: key)
        NotificationCenter.default.post(name: .bbLocaleChanged, object: nil)
    }

    static func t(_ k: String, _ params: [String: String] = [:]) -> String {
        let table = strings[locale] ?? strings["en"]!
        var s = table[k] ?? strings["en"]?[k] ?? k
        for (name, value) in params { s = s.replacingOccurrences(of: "{\(name)}", with: value) }
        return s
    }
}

extension Notification.Name { static let bbLocaleChanged = Notification.Name("bb.locale.changed") }

extension Loc {
    // Only the keys used by shipped native screens. Expand per wave.
    static let strings: [String: [String: String]] = [
        "en": [
            // Launch splash
            "m_splash_title": "Private Board", "m_splash_slogan": "A meeting, not a chatbot.",
            // Report style picker
            "m_rep_style": "STYLE", "m_rep_auto": "Auto",
            "m_mini_playing": "NOW PLAYING",
            // Brief-generation animation (mirrors the desktop report-build prompts)
            "m_bg_kicker": "{chair} is preparing the minutes", "m_bg_chair_fallback": "The chair",
            "m_bg_elapsed": "{t} elapsed", "m_bg_step": "STEP",
            "m_bg_extract_label": "Reading what each director said",
            "m_bg_compose_label": "Picking the report shape",
            "m_bg_anchor_label": "Setting the anchor",
            "m_bg_findings_label": "Sketching findings",
            "m_bg_cluster_label": "Mapping consensus + dissent",
            "m_bg_actions_label": "Drafting actions + risks",
            "m_bg_write_label": "Writing the report",
            "m_bg_write_magazine": "Composing the magazine",
            "m_bg_write_newspaper": "Composing the newspaper",
            "m_bg_write_ppt": "Composing the deck",
            "m_bg_sub_extract_0": "Re-reading each director's contributions",
            "m_bg_sub_extract_1": "Tagging signals by lens (data / dissent / narrative / structural)",
            "m_bg_sub_extract_2": "Tightening to 2–4 signals per director",
            "m_bg_sub_compose_0": "Picking the spine for this brief",
            "m_bg_sub_compose_1": "Choosing which component blocks fit",
            "m_bg_sub_compose_2": "Sizing density and rhythm",
            "m_bg_sub_anchor_0": "Reading the takeaway",
            "m_bg_sub_anchor_1": "Sizing the confidence call",
            "m_bg_sub_anchor_2": "Setting the working hypothesis",
            "m_bg_sub_findings_0": "Pulling out the headline findings",
            "m_bg_sub_findings_1": "Cross-checking each finding to the anchor",
            "m_bg_sub_findings_2": "Tightening 3 → 2 if a finding wobbles",
            "m_bg_sub_cluster_0": "Mapping where the directors converged",
            "m_bg_sub_cluster_1": "Surfacing the central tension",
            "m_bg_sub_cluster_2": "Spotting positions that didn't quite resolve",
            "m_bg_sub_actions_0": "Drafting recommendations",
            "m_bg_sub_actions_1": "Mapping the pre-mortem",
            "m_bg_sub_actions_2": "Surfacing the new questions the room opened",
            "m_bg_sub_write_0": "Writing the Bottom Line",
            "m_bg_sub_write_1": "Composing the Frame Shift section",
            "m_bg_sub_write_2": "Writing the 3 Headline Findings",
            "m_bg_sub_write_3": "Drafting Convergence + Divergence",
            "m_bg_sub_write_4": "Composing Recommendations",
            "m_bg_sub_write_5": "Surfacing New Questions",
            "m_bg_sub_write_6": "Drafting the Strategic Planning Assumption",
            "m_bg_sub_write_7": "Polishing the final pass",
            // Voice clone
            "m_ap_voice_clone": "Clone voice",
            "m_vc_title": "Clone · {name}",
            "m_vc_record": "Record", "m_vc_import": "Import",
            "m_vc_script_label": "READ THIS ALOUD",
            "m_vc_recording": "Recording…", "m_vc_recorded": "Sample ready", "m_vc_tap_record": "Tap to record",
            "m_vc_playback": "Play back", "m_vc_stop": "Stop", "m_vc_rerecord": "Re-record",
            "m_vc_mic_denied": "Microphone access denied. Enable it in Settings to record.",
            "m_vc_pick_file": "Choose audio file", "m_vc_import_hint": "10s–3min of clear speech. mp3 / m4a / wav, up to 20MB.",
            "m_vc_label_ph": "Cloned voice name (optional)",
            "m_vc_group_ph": "MiniMax Group ID (if your key isn't a JWT)",
            "m_vc_group_hint": "Required only if your MiniMax key isn't a JWT. Find it in the MiniMax console.",
            "m_vc_start": "Start cloning",
            "m_vc_stage_prepare": "Preparing sample", "m_vc_stage_upload": "Uploading", "m_vc_stage_clone": "Cloning voice",
            "m_vc_cloned_kicker": "// CLONED", "m_vc_cloned_sub": "Cloned · {name}",
            "m_vc_sample_label": "PREVIEW LINE", "m_vc_sample_ph": "Type a line to hear…",
            "m_vc_sample_hint": "Edit the line, then tap play to hear the cloned voice.",
            "m_vc_sample_default": "I'm {name}, a member of your private boardroom. Looking forward to working with you.",
            "m_vc_apply": "Apply this voice", "m_vc_retry": "Retry",
            "m_vc_err_group": "MiniMax needs a Group ID. Paste it above, or re-paste a JWT-format key.",
            "m_vc_err_auth": "The provider rejected the API key. Re-check it in voice settings.",
            "m_vc_err_quota": "Your provider balance / plan doesn't allow voice cloning.",
            "m_vc_err_voiceid": "The provider rejected the generated voice id. Try a different name.",
            "m_vc_err_short": "The sample is too short to clone from.",
            "m_vc_err_long": "The sample exceeds 20MB. Trim it and try again.",
            "m_vc_err_unsupported": "The active voice provider doesn't support cloning.",
            "m_vc_err_unknown": "Cloning failed. Please try again.",
            // Home / tabs
            "m_home_rooms": "Rooms", "m_home_directors": "Directors", "m_home_new": "New",
            "m_home_active": "Active", "m_home_today": "Today", "m_home_week": "This Week", "m_home_earlier": "Earlier",
            "m_home_settings_aria": "Settings", "m_home_create_aria": "Create",
            "m_home_rooms_count": "{n} rooms", "m_home_dirs_count": "{n} directors",
            "m_rooms_empty": "No rooms yet — create one.",
            // Empty-rooms onboarding · gamified starter plays
            "m_rooms_start_kicker": "GET STARTED",
            "m_rooms_start_head": "Convene your first board.",
            "m_rooms_start_sub": "Pick a play to start — we'll set the cast and tone. Or tap + to compose your own.",
            "scn_brainstorm_tag": "Product · Brainstorm",
            "scn_brainstorm_head": "Three angles on one idea, until it sharpens.",
            "scn_brainstorm_body": "First Principles, User-Empathy, and Long Horizon ride the same idea from three directions until the shape of the bet is unmistakable.",
            "scn_brainstorm_subj": "Brainstorm a new product angle — what would 10x adoption look like, and what has to be true?",
            "scn_pitch_tag": "Investor · Pitch",
            "scn_pitch_head": "Pitch your toughest VC, before the real meeting.",
            "scn_pitch_body": "Three skeptical partners tear into your deck — moat thesis, unit economics, founder-market fit. Walk out with the questions you couldn't answer.",
            "scn_pitch_subj": "Pitch our latest deck — break the moat thesis, the unit economics, and the founder-market fit.",
            "scn_audit_tag": "Audit · Find Flaws",
            "scn_audit_head": "An adversarial audit of the plan you almost shipped.",
            "scn_audit_body": "Three directors read your plan as if they had to break it in production — blockers, majors, minors, and which assumption snaps first.",
            "scn_audit_subj": "Audit this quarter's plan — list the blockers, the majors, and the minors. Which assumption breaks first?",
            "scn_fork_tag": "Decision · Fork",
            "scn_fork_head": "Force the choice between two real options.",
            "scn_fork_body": "Three directors argue each branch from a different lens — costs, second-order effects, what it means if you're wrong. Decide at the end, not before.",
            "scn_fork_subj": "Two real options on the table — what does each branch look like at the time horizon that matters, and how do I tell when I'm wrong?",
            // No API key gate
            "m_nokey_title": "Set up an API key first",
            "m_nokey_msg": "Convening a board needs a model key. Add one in Settings → API keys, then try again.",
            "m_nokey_go": "Open API keys",
            // First-run onboarding (5 steps · mirrors desktop)
            "onb_step": "Step {n} of 5", "onb_back": "Back", "onb_continue": "Continue",
            "onb_name_kicker": "00 · SIT DOWN", "onb_name_head": "How should the room call you?",
            "onb_name_sub": "From here on, this is your room.", "onb_name_ph": "e.g. Kay", "onb_name_cta": "Step in",
            "onb_phil_kicker": "01 · A MEETING, NOT A CHATBOT",
            "onb_phil_head": "You convene stubborn advisors and let them argue, in front of you, over a question that matters.",
            "onb_phil_body": "Three acts · convene · sharpen · adjourn. You sit as chair, the directors take sides, and on adjourn you walk away with a brief in hand.",
            "onb_phil_note": "Not a chatbot. The directors don't agree with you — they pressure-test the question until it sharpens.",
            "onb_key_kicker": "02 · HAND OVER A KEY", "onb_key_head": "Pick one brain — or pick many.",
            "onb_key_sub": "Your key stays on this device. We never upload it.",
            "onb_key_multi": "One key, every model", "onb_key_direct": "Or a direct provider",
            "onb_key_field": "{provider} API key", "onb_key_configured": "{provider} key configured",
            "onb_key_saving": "Saving…", "onb_key_fail": "Couldn't save that key — check it and try again.",
            "key_validate_empty": "Enter an API key.",
            "key_validate_whitespace": "Remove spaces from the key — pasted text often picks up a trailing space.",
            "key_validate_prefix": "{label} keys should start with \u{201C}{prefix}\u{201D}.",
            "key_validate_length": "Looks too short for {label} — real keys run at least {minLen} characters.",
            "onb_voice_kicker": "03 · GIVE THEM A VOICE · OPTIONAL", "onb_voice_head": "Want them to speak aloud?",
            "onb_voice_sub": "Add a TTS key and the boardroom turns into a round table — directors take seats, raise their head to speak, fade back to listen. Skip if you'd rather stay text-only; flip it on anytime in Settings.",
            "onb_voice_skip": "Skip for now", "onb_voice_skipcta": "Skip", "onb_voice_save": "Save & continue",
            "onb_cast_kicker": "04 · YOUR BOARD",
            "onb_cast_head": "Chair runs the room. Directors disagree. The brief closes the loop.",
            "onb_cast_body": "By default the chair picks three directors for you — you can also pick your own. That choice, and your question, happen in the composer next.",
            "onb_cast_preview": "PREVIEW · PICK LATER IN THE COMPOSER", "onb_cast_flow": "NEXT · IN THE COMPOSER",
            "onb_cast_s1": "Write your question", "onb_cast_s2": "Chair picks 3 directors", "onb_cast_s3": "Hit Convene",
            "onb_cast_cta": "I'm ready",
            "m_dir_most_used": "Most used", "m_dir_all": "Directors", "m_dir_rooms": "rooms",
            "m_dir_sort_newest": "Newest", "m_dir_sort_oldest": "Oldest", "m_dir_sort_name": "Name",
            // Room cards
            "m_rc_live": "Live", "m_rc_paused": "Paused", "m_rc_adjourned": "Adjourned",
            "m_rc_voice": "Voice", "m_rc_text": "Text", "m_rc_report_badge": "REPORT",
            "m_rc_meta": "{delivery} · {n} directors · {ago}",
            "m_rc_meta_noago": "{delivery} · {n} directors",
            // Connect
            "connect_title": "Connect to your boardroom",
            "connect_hint": "Run the desktop server with `boardroom --host 0.0.0.0`, then enter your computer's address on this Wi-Fi.",
            "connect_btn": "Connect", "connect_demo": "Explore a demo",
            "connect_connecting": "Connecting…", "connect_bad": "That doesn't look like a valid address.",
            // Room chrome / dock
            "m_room_back_aria": "Back to rooms", "m_room_menu_aria": "Room menu",
            "m_dock_interject_aria": "Raise hand to interject", "m_dock_playpause_aria": "Pause / play",
            "m_dock_rate_aria": "Playback speed", "m_dock_collapse_aria": "Hide controls",
            "m_dock_expand_aria": "Show controls",
            "m_queue_aria": "Speaking queue",
            "m_queue_title": "Speaking order",
            "m_queue_speaking": "Speaking", "m_queue_standby": "Standby", "m_queue_done": "Done", "m_queue_next": "Next",
            "m_composer_ask": "Ask the board…", "m_composer_clarify": "Reply to the chair…",
            "m_send_fail": "Couldn't send — try again.",
            "m_ask_q": "{who} is speaking. Jump in now, or wait your turn?",
            "m_ask_interrupt": "Interrupt now", "m_ask_after": "After {who}", "m_ask_cancel": "Cancel",
            "m_adj_replay": "Replay", "m_adj_followup": "Follow-up", "m_adj_report": "Report", "m_adj_transcript": "Transcript",
            "m_adj_stop": "Stop", "m_adj_followup_ph": "Ask a follow-up — convenes a new room with this cast…",
            "m_adj_convening": "Convening…",
            // Status
            "m_status_live": "Live", "m_status_paused": "Paused", "m_status_pausing": "Pausing", "m_status_resuming": "Resuming",
            // Menu
            "m_menu_title": "Room", "m_menu_settings": "Room settings", "m_menu_cast": "Manage cast",
            "m_menu_adjourn": "Adjourn & file report", "m_menu_genreport": "View report",
            "m_menu_pause": "Pause room", "m_menu_resume": "Resume room", "m_menu_delete": "Delete room",
            "m_menu_queue": "Speaking order",
            "m_sheet_queue": "Queue", "m_queue_empty": "No speakers queued yet.",
            "m_q_speaking": "speaking", "m_q_framing": "framing", "m_q_up_next": "up next", "m_q_spoke": "spoke",
            "m_round_done": "Round complete.", "m_continue": "Continue", "m_kp_adjourn": "Adjourn",
            "m_round_sep": "Round {n}", "m_q_round": "Round {n}",
            "m_chair_room_note": "Room note", "m_chair_direct": "Direct from chair",
            "m_chair_pend_kicker": "Chair", "m_chair_pend_default": "Chair is preparing",
            "m_chair_pend_clarify": "Chair is reviewing your question",
            "m_chair_pend_round_end": "Chair is wrapping the round",
            "m_chair_pend_convening": "Chair is assembling the board",
            "m_tts_billing_title": "Voice synthesis paused",
            "m_tts_billing_msg": "{provider} reported an insufficient balance, so the directors can't speak aloud. Recharge {provider}, or switch to another voice provider in Settings → API keys.",
            "m_tts_billing_recharge": "Recharge", "m_tts_billing_dismiss": "Got it",
            "m_billing_title": "Out of balance",
            "m_llm_billing_msg": "{provider} reported an insufficient balance or exhausted quota, so the directors can't respond. Top up {provider}, or switch to another provider's key in Settings → API keys.",
            "m_provider_generic": "the provider",
            "m_chair_billing_kicker": "▸ billing · attention needed",
            "m_auth_title": "API key rejected",
            "m_auth_msg": "The provider rejected the API key — it may be invalid or removed. Re-check it in Settings → API keys.",
            "m_auth_cta": "Open API keys",
            "m_net_title": "Network timeout",
            "m_net_msg": "Couldn't reach the model in time — a network blip or the provider was slow. Tap Retry, or try again in a moment.",
            "m_reconnect_title": "Connection lost",
            "m_reconnect_msg": "The on-device service stopped responding after the app resumed. Tap Retry to reconnect.",
            "m_brief_badge_generating": "Generating report…",
            "m_brief_badge_ready": "Report ready · tap to open",
            "m_brief_badge_failed": "Report failed · tap to retry",
            "np_thinking": "thinking…", "np_in_session": "In session",
            "rt_phase_next_speaker": "Choosing who speaks next…", "rt_phase_vote_summary": "Summing up the round…",
            "rt_phase_searching": "Searching the web…", "rt_phase_catching_up": "Catching up on the room…",
            "rt_phase_clarify": "Getting ready…", "rt_thinking_stalled": "No response yet — still waiting",
            "m_adjourn_file": "Adjourn & file report", "m_vote_adjourn": "Call the vote",
            "m_adjourn_title": "Adjourn the room", "m_adjourn_format": "Report format",
            "m_adjourn_supplement": "Anything to emphasize? (optional)",
            "m_adjourn_supplement_ph": "e.g. focus on the pricing risk; lead with the decision",
            "m_adjourn_generate": "Generate report", "m_adjourn_end": "End without report",
            "m_round_reopen": "Round wrapped · review",
            "kp_eyebrow_vote": "▸ key points · vote what you want pursued",
            "kp_eyebrow_drafting": "▸ key points · drafting…",
            "kp_eyebrow_degraded": "▸ key points · couldn't be parsed from this round",
            "kp_vote_more": "more", "kp_vote_drop": "drop",
            "kp_vote_aria_up": "Interested", "kp_vote_aria_down": "Not interested",
            "kp_shift_prefix": "▸ chair suggests · switch tone to ",
            "kp_switch_to": "Switch to {mode}", "kp_keep_mode": "Keep {mode}",
            "kp_mode_current": "current", "kp_btn_adjourn": "Adjourn", "kp_vote_fail": "Vote failed",
            "m_delete_confirm": "Delete \u{201C}{subject}\u{201D}? This can't be undone.", "m_delete_do": "Delete",
            // New room
            "m_nr_title": "New room", "m_nr_subject": "Subject", "m_nr_subject_ph": "What should the board decide?",
            "m_nr_format": "Format", "m_nr_tone": "Tone", "m_nr_board": "Board",
            "m_nr_auto": "Auto-pick", "m_nr_auto_hint": "The chair assembles the board from the registry to fit your question.",
            "m_nr_choose": "Choose", "m_nr_choose_prompt": "Choose directors",
            "m_nr_or_choose": "Or choose directors", "m_nr_convene": "Convene room", "m_nr_convening": "Convening…",
            "m_nr_directors": "Directors · {n}", "m_dpick_done": "Done",
            "m_toast_pick_two": "Pick at least two directors.",
            // New director
            "m_na_title": "New director", "m_na_desc_label": "Description",
            "m_na_desc_ph": "e.g. A ruthless pricing strategist who reasons from unit economics and distrusts vanity metrics — pushes the board to name the one number that decides it.",
            "m_na_build_mode": "Build mode", "m_na_signal": "Signal", "m_na_signal_deck": "Fast draft · a few seconds",
            "m_na_full": "Full persona", "m_na_full_deck": "Deep build · web-grounded",
            "m_na_generate": "Generate director", "m_na_manual": "Fill in manually instead",
            "m_na_gen_fail": "Generation failed — try a more concrete description.", "m_na_generating": "Drafting the director…",
            "m_na_sig_step": "Signal build · step {n} of {total}",
            "m_na_p1": "Drafting the profile", "m_na_p2": "Naming the director", "m_na_p3": "Writing the bio",
            "m_na_p4": "Composing the instruction", "m_na_p5": "Picking the model voice", "m_na_p6": "Polishing",
            "m_na_name": "Name", "m_na_role": "Role tag", "m_na_intro_ph": "One line on how they think",
            "m_na_instr_ph": "Role · objectives · voice · boundaries the director should follow",
            "m_na_save": "Save director", "m_na_saving": "Saving…",
            "m_na_avatar": "Avatar", "m_na_avatar_hint": "A 3D portrait — dice re-rolls, tap to customise.",
            // 3D avatar customiser
            "m_av_title": "Customise avatar", "m_av_save": "Use",
            "m_av_model": "Body", "m_av_hair": "Hair", "m_av_accessory": "Accessory",
            "m_av_brow": "Brows", "m_av_eye": "Eyes", "m_av_beard": "Beard",
            "m_av_tie": "Neck", "m_av_top": "Top", "m_av_bottom": "Bottom",
            "m_av_c_skin": "Skin", "m_av_c_hair": "Hair colour", "m_av_c_brow": "Brow colour",
            "m_av_c_beard": "Beard colour", "m_av_c_top": "Top colour", "m_av_c_bottom": "Bottom colour",
            "m_av_c_tie": "Neck colour", "m_av_c_eye": "Eye colour",
            "m_av_customise": "Customise 3D avatar",
            // 3D avatar customiser · desktop parity (av3d_* · mirror avatar3d-editor.js)
            "av3d_kicker": "Customize", "av3d_rand": "Randomize", "av3d_save": "Save", "av3d_cancel": "Cancel",
            "av3d_load_failed": "The 3D avatar didn't load. Tap to try again.", "av3d_retry": "Retry",
            "av3d_sec_head": "Head", "av3d_sec_outfit": "Outfit",
            "av3d_lab_skin": "Skin", "av3d_lab_hair": "Hair", "av3d_lab_brow": "Brow", "av3d_lab_beard": "Beard",
            "av3d_lab_eye": "Eyes", "av3d_lab_top": "Top", "av3d_lab_bottom": "Bottom", "av3d_lab_tie": "Tie",
            "av3d_lab_accessory": "Accessory",
            "av3d_opt_hairStyle_glasses": "Bun", "av3d_opt_hairStyle_casual": "Tousled", "av3d_opt_hairStyle_street": "Short crop",
            "av3d_opt_hairStyle_royal": "Medium + bangs", "av3d_opt_hairStyle_xmas": "Long", "av3d_opt_hairStyle_style6": "Low ponytail",
            "av3d_opt_hairStyle_style7": "Side part", "av3d_opt_hairStyle_style8": "Bear crop", "av3d_opt_hairStyle_style9": "Buzz + sides",
            "av3d_opt_hairStyle_none": "Bald",
            "av3d_opt_browStyle_default": "Standard", "av3d_opt_browStyle_royal": "Bold", "av3d_opt_browStyle_style6": "Thin",
            "av3d_opt_browStyle_style7": "Soft", "av3d_opt_browStyle_style8": "Heavy",
            "av3d_opt_eyeStyle_default": "Default", "av3d_opt_eyeStyle_casual": "Round", "av3d_opt_eyeStyle_street": "Narrow",
            "av3d_opt_eyeStyle_royal": "Almond", "av3d_opt_eyeStyle_style7": "Gentle", "av3d_opt_eyeStyle_style8": "Beady",
            "av3d_opt_eyeStyle_style9": "Sharp", "av3d_opt_eyeStyle_style10": "Dot",
            "av3d_opt_beardStyle_none": "None", "av3d_opt_beardStyle_style8": "Full beard", "av3d_opt_beardStyle_style9": "Mustache",
            "av3d_opt_beardStyle_style10": "Whiskers",
            "av3d_opt_tieStyle_none": "None", "av3d_opt_tieStyle_royal": "Necktie", "av3d_opt_tieStyle_xmas": "Bow tie",
            "av3d_opt_topStyle_glasses": "Blue top", "av3d_opt_topStyle_casual": "Black tee", "av3d_opt_topStyle_style6": "Pinafore",
            "av3d_opt_topStyle_style7": "Long sleeve",
            "av3d_opt_bottomStyle_casual": "White shorts", "av3d_opt_bottomStyle_street": "Street shorts",
            "av3d_opt_accessory_none": "None", "av3d_opt_accessory_glasses": "Glasses", "av3d_opt_accessory_shades": "Shades",
            "av3d_opt_accessory_headphones": "Headphones", "av3d_opt_accessory_cap": "Cap", "av3d_opt_accessory_crown": "Crown",
            "av3d_opt_accessory_santa": "Santa hat", "av3d_opt_accessory_tophat": "Top hat", "av3d_opt_accessory_mask": "Mask",
            "av3d_opt_accessory_blindfold": "Blindfold", "av3d_opt_accessory_star": "Star", "av3d_opt_accessory_anger": "Anger",
            "av3d_opt_accessory_redcheek": "Blush", "av3d_opt_accessory_bearsuit": "Bear onesie", "av3d_opt_accessory_pikasuit": "Pikachu coat",
            "m_model_director": "Director model", "m_model_director_hint": "The LLM that powers this director's turns.",
            "m_toast_describe_first": "Describe the director first.",
            // Tones / intensities
            "m_set_tone": "Tone", "m_set_intensity": "Intensity",
            "m_set_delivery": "Delivery", "m_set_voice": "Voice mode",
            "m_set_voice_sub": "Read replies aloud (TTS). Off = text only.",
            "m_set_vote": "Vote phase",
            "m_vote_auto": "Auto", "m_vote_manual": "Manual",
            "m_vote_auto_sub": "The chair wraps each round and opens the vote automatically.",
            "m_vote_manual_sub": "Directors keep going across rounds — you open the vote when you're ready.",
            "m_vote_end_round": "End round & vote",
            "rt_vote_confirm_kicker": "Round can wrap", "rt_vote_confirm_q": "Call the vote now?",
            "rt_vote_confirm_go": "Call vote", "rt_vote_confirm_dismiss": "Keep going",
            "sa_head": "session analytics", "sa_stamp": "closed",
            "sa_tokens": "tokens", "sa_msgs": "msgs", "sa_rounds": "rounds", "sa_duration": "duration",
            "sa_model_head": "Model usage", "sa_valued_head": "What you valued",
            "m_tone_brainstorm": "Brainstorm", "m_tone_constructive": "Constructive", "m_tone_research": "Research",
            "m_tone_debate": "Debate", "m_tone_critique": "Critique",
            "m_int_calm": "Calm", "m_int_sharp": "Sharp", "m_int_terse": "Terse",
            "m_set_cast_save": "Save cast", "m_set_cast_min": "Keep at least one director.",
            "m_set_adjourned_note": "This room is adjourned · settings are read-only.",
            // Agent profile
            "m_ap_title": "Director", "m_ap_moderator": "Moderator",
            "m_ap_radar": "Ability radar", "m_ap_brief": "Operating brief",
            "m_ap_activity": "Activity", "m_ap_stat_rooms": "Boardrooms", "m_ap_stat_rounds": "Rounds spoken",
            "m_ap_stat_tokens": "Tokens",
            "m_ap_available": "Available", "m_ap_model": "Model",
            "m_ap_bio": "Bio", "m_ap_role": "Role", "m_ap_instruction": "Instruction",
            "m_ap_bio_empty": "No bio yet — tap Edit to add one.", "m_ap_instr_empty": "No instruction set — tap Edit to add one.",
            "m_ap_websearch": "Web search", "m_ap_websearch_sub": "Let this director look things up mid-room",
            "m_ap_edit": "Edit", "m_ap_save": "Save",
            "m_ap_rename": "Rename director", "m_ap_name": "Name",
            "m_ap_del_dir": "Delete director", "m_ap_del_confirm": "Delete {name}? This can't be undone.",
            "m_ap_show_more": "Show more", "m_ap_show_less": "Show less",
            "m_ap_rules": "Rules", "m_ap_rule_add": "Add rule", "m_ap_rule_ph": "An atomic constraint…",
            "m_ap_mem_chair": "Memory · about you", "m_ap_notes_none": "No notes yet.",
            "m_ap_note_add": "Add note", "m_ap_note": "Note",
            "m_ap_voice": "Voice", "m_ap_voice_none": "Not set", "m_ap_voice_pick": "Choose a voice",
            "m_ap_voice_empty": "No voices available — configure a voice provider in Settings.",
            "m_ap_emotion": "Emotion", "m_ap_emotion_default": "Default",
            "m_ap_voice_preview": "Preview voice", "m_ap_voice_stop": "Stop", "m_ap_voice_loading": "Loading…",
            // Persona dossier (full-persona directors)
            "m_dossier_title": "Persona dossier", "m_dossier_kicker": "PERSONA · 7-PHASE BUILD",
            "m_dossier_built": "Built · {date}", "m_dossier_open": "Open dossier",
            "m_dossier_concepts": "Concepts", "m_dossier_referents": "Referents", "m_dossier_rules": "Rules",
            "m_dossier_voice": "Voice ex.", "m_dossier_checks": "Checks", "m_dossier_evals": "Evals",
            "m_dossier_classified": "CLASSIFIED · DIRECTOR DOSSIER",
            "m_dossier_spec": "Persona spec", "m_dossier_lineage": "Intellectual lineage",
            "m_dossier_loadbearing": "Load-bearing concepts", "m_dossier_referentset": "Referent set",
            "m_dossier_failure": "Failure modes", "m_dossier_contrarian": "Contrarian takes",
            "m_dossier_rules_h": "Behavioural rules", "m_dossier_fewshot": "Few-shot examples",
            "m_dossier_reflection": "Reflection checklist", "m_dossier_reflection_sub": "Run silently before every turn.",
            "m_dossier_eval": "Eval set", "m_dossier_eval_sub": "Test prompts + expected signatures.",
            "m_dossier_example": "Example {n}", "m_dossier_scenario": "Scenario",
            "m_dossier_generic": "Generic AI", "m_dossier_persona": "This director",
            "m_dossier_rationale": "Why", "m_dossier_expected": "Expected signature",
            "m_dossier_always": "Always", "m_dossier_never": "Never", "m_dossier_when": "When",
            "m_dossier_empty": "This director wasn't built with the full-persona pipeline.",
            // Report
            "m_rep_title": "Report", "m_rep_loading": "Loading the report…", "m_rep_none": "No report filed for this room yet.",
            "m_rep_generating": "Filing the report…", "m_rep_gen_btn": "Generate report",
            // Settings hub
            "m_prefs_title": "Settings", "m_prefs_keys": "API keys", "m_prefs_usage": "Usage", "m_prefs_language": "Language",
            "m_prefs_usage_sub": "{tokens} tokens · this month",
            "m_prefs_avatar": "My avatar",
            "m_av_edit": "Customize avatar",
            "m_av_foot": "Your 3D figure in the room. Tap to open the editor — pick a body, hair, outfit and colours.",
            // Usage panel
            "m_usage_title": "Usage", "m_usage_total_sub": "tokens · this month", "m_usage_by_model": "By model",
            "m_usage_none": "No usage data available.", "m_usage_loading": "Loading usage…",
            "m_usage_all": "All · cumulative", "m_usage_cum": "Cumulative", "m_usage_last14": "Last 14 days",
            "m_usage_unit": "tokens", "m_usage_meta_models": "Models", "m_usage_meta_agents": "Agents",
            "m_usage_meta_active": "Active", "m_usage_top": "Top consumers", "m_usage_chair": "Chair",
            "m_usage_director": "Director", "m_usage_silent": "+{n} used no tokens",
            "m_usage_retired": "{agents} retired · {tokens} tokens folded in", "m_usage_day_none": "No usage on this day.",
            "m_lang_title": "Language",
            // API keys
            "m_keys_title": "API keys", "m_keys_none": "No keys yet.", "m_keys_add": "Add key",
            "m_credetail_provider": "Provider", "m_credetail_status": "Status", "m_credetail_active": "Active", "m_credetail_setactive": "Set as active",
            "m_keys_foot": "Keys are stored on your boardroom server. After saving, only a masked preview is shown — never the plaintext. Tap a key to make it the active one for that category.",
            "m_cat_llm": "LLM provider", "m_cat_voice": "Voice · TTS", "m_cat_search": "Web search",
            "m_cat_llm_hint": "Pick one provider the board routes every turn through. Carriers reach many model families from a single key; direct keys reach one family.",
            "m_cat_voice_hint": "Spoken voice for live voice rooms — the active key drives every director's speech.",
            "m_cat_search_hint": "Lets directors cite live sources during research-tone rooms.",
            "m_addkey_carriers": "Carriers · one key, many models", "m_addkey_direct": "Direct providers",
            "m_addkey_provider": "Provider", "m_addkey_label": "Label · optional", "m_addkey_label_ph": "e.g. Personal, Work",
            "m_addkey_key": "API key", "m_addkey_save": "Save key", "m_addkey_eye_aria": "Show or hide key",
            "m_toast_paste_key": "Paste an API key first.",
            // MiniMax host region
            "m_addkey_group": "Group ID", "m_addkey_group_ph": "MiniMax GroupID (optional)",
            "m_addkey_group_hint": "Only needed if your MiniMax key doesn't already embed the GroupID. Required for voice cloning.",
            "m_vc_group_needed_title": "MiniMax Group ID needed",
            "m_vc_group_needed_msg": "Voice cloning needs your MiniMax GroupID. Add it in Settings → API keys → MiniMax, then try again.",
            "m_addkey_region": "Region", "m_addkey_region_cn": "China", "m_addkey_region_intl": "International",
            "m_addkey_region_cn_host": "api.minimaxi.com", "m_addkey_region_intl_host": "api.minimax.io",
            "m_addkey_region_hint": "Pick the host your MiniMax account belongs to — keys from platform.minimaxi.com are China, platform.minimax.io are International.",
            // Common
            "common_done": "Done", "common_cancel": "Cancel", "common_retry": "Retry", "common_server": "Server", "common_ok": "OK",
        ],
        "zh": [
            "m_splash_title": "Private Board", "m_splash_slogan": "一场会议,而非聊天机器人。",
            // Report style picker
            "m_rep_style": "样式", "m_rep_auto": "自动",
            "m_mini_playing": "正在播放",
            // Brief-generation animation
            "m_bg_kicker": "{chair} 正在整理会议纪要", "m_bg_chair_fallback": "主席",
            "m_bg_elapsed": "已用时 {t}", "m_bg_step": "步骤",
            "m_bg_extract_label": "正在阅读每位董事的发言",
            "m_bg_compose_label": "正在选择报告结构",
            "m_bg_anchor_label": "正在确立核心结论",
            "m_bg_findings_label": "正在勾勒关键发现",
            "m_bg_cluster_label": "正在梳理共识与分歧",
            "m_bg_actions_label": "正在起草行动与风险",
            "m_bg_write_label": "正在撰写报告",
            "m_bg_write_magazine": "正在编排杂志",
            "m_bg_write_newspaper": "正在排版报纸",
            "m_bg_write_ppt": "正在制作幻灯片",
            "m_bg_sub_extract_0": "重读每位董事的发言",
            "m_bg_sub_extract_1": "按视角标注信号(数据 / 异见 / 叙事 / 结构)",
            "m_bg_sub_extract_2": "每位董事精炼到 2–4 条信号",
            "m_bg_sub_compose_0": "为本份纲要选定主线",
            "m_bg_sub_compose_1": "挑选合适的组件模块",
            "m_bg_sub_compose_2": "调校密度与节奏",
            "m_bg_sub_anchor_0": "提炼核心结论",
            "m_bg_sub_anchor_1": "评估信心程度",
            "m_bg_sub_anchor_2": "确立工作假设",
            "m_bg_sub_findings_0": "提取头条发现",
            "m_bg_sub_findings_1": "将每条发现与核心结论交叉校验",
            "m_bg_sub_findings_2": "若发现不稳则由 3 收敛到 2",
            "m_bg_sub_cluster_0": "梳理董事们的共识所在",
            "m_bg_sub_cluster_1": "浮现核心张力",
            "m_bg_sub_cluster_2": "标记尚未完全化解的立场",
            "m_bg_sub_actions_0": "起草建议",
            "m_bg_sub_actions_1": "推演事前验尸(pre-mortem)",
            "m_bg_sub_actions_2": "浮现房间打开的新问题",
            "m_bg_sub_write_0": "撰写「核心结论」",
            "m_bg_sub_write_1": "撰写「视角转变」一节",
            "m_bg_sub_write_2": "撰写 3 条头条发现",
            "m_bg_sub_write_3": "起草「共识与分歧」",
            "m_bg_sub_write_4": "撰写「建议」",
            "m_bg_sub_write_5": "浮现「新问题」",
            "m_bg_sub_write_6": "起草「战略规划假设」",
            "m_bg_sub_write_7": "做最后润色",
            // Voice clone
            "m_ap_voice_clone": "克隆声音",
            "m_vc_title": "克隆 · {name}",
            "m_vc_record": "录音", "m_vc_import": "导入",
            "m_vc_script_label": "请朗读这段文字",
            "m_vc_recording": "录音中…", "m_vc_recorded": "样本就绪", "m_vc_tap_record": "点击开始录音",
            "m_vc_playback": "试听", "m_vc_stop": "停止", "m_vc_rerecord": "重新录制",
            "m_vc_mic_denied": "麦克风权限被拒绝,请在系统设置中开启后再录音。",
            "m_vc_pick_file": "选择音频文件", "m_vc_import_hint": "10秒–3分钟清晰人声。mp3 / m4a / wav,最大 20MB。",
            "m_vc_label_ph": "克隆音色名称(可选)",
            "m_vc_group_ph": "MiniMax Group ID(密钥非 JWT 时填)",
            "m_vc_group_hint": "仅当 MiniMax 密钥不是 JWT 格式时需要,可在 MiniMax 控制台查看。",
            "m_vc_start": "开始克隆",
            "m_vc_stage_prepare": "准备样本", "m_vc_stage_upload": "上传中", "m_vc_stage_clone": "克隆音色",
            "m_vc_cloned_kicker": "// 已克隆", "m_vc_cloned_sub": "已克隆 · {name}",
            "m_vc_sample_label": "试听文本", "m_vc_sample_ph": "输入一句话试听…",
            "m_vc_sample_hint": "编辑文本后,点击播放即可听克隆音色。",
            "m_vc_sample_default": "我是 {name},你私人董事会的一员,很期待与你共事。",
            "m_vc_apply": "应用该音色", "m_vc_retry": "重试",
            "m_vc_err_group": "MiniMax 需要 Group ID,请在上方填写,或重新粘贴 JWT 格式的密钥。",
            "m_vc_err_auth": "服务商拒绝了该 API 密钥,请在语音设置中重新检查。",
            "m_vc_err_quota": "你的服务商余额 / 套餐不支持声音克隆。",
            "m_vc_err_voiceid": "服务商拒绝了生成的音色 ID,换个名称重试。",
            "m_vc_err_short": "样本太短,无法克隆。",
            "m_vc_err_long": "样本超过 20MB,请裁剪后重试。",
            "m_vc_err_unsupported": "当前语音服务商不支持克隆。",
            "m_vc_err_unknown": "克隆失败,请重试。",
            "m_home_rooms": "房间", "m_home_directors": "董事", "m_home_new": "新建",
            "m_home_active": "进行中", "m_home_today": "今天", "m_home_week": "本周", "m_home_earlier": "更早",
            "m_home_settings_aria": "设置", "m_home_create_aria": "新建",
            "m_home_rooms_count": "{n} 个房间", "m_home_dirs_count": "{n} 位董事",
            "m_rooms_empty": "还没有房间——新建一个。",
            // 空房间引导 · 游戏化的开局玩法
            "m_rooms_start_kicker": "开始使用",
            "m_rooms_start_head": "召集你的第一场董事会",
            "m_rooms_start_sub": "选一个玩法开始 —— 我们会配好董事阵容和基调。或点 + 自己组局。",
            "scn_brainstorm_tag": "产品 · 头脑风暴",
            "scn_brainstorm_head": "三个角度打磨同一个点子",
            "scn_brainstorm_body": "First Principles、User-Empathy、Long Horizon 从原理、真实用户、十年尺度三个方向反复推演，直到这个赌注的形状清晰可见。",
            "scn_brainstorm_subj": "头脑风暴一个新产品方向 —— 10 倍增长会是什么样，又有哪些前提必须成立？",
            "scn_pitch_tag": "融资 · 路演",
            "scn_pitch_head": "在真正见投资人前，先过最毒舌的一关",
            "scn_pitch_body": "三位挑剔的合伙人逐条拆你的 deck —— 护城河、单位经济、创始人与市场的契合度。带着你答不上来的问题离场。",
            "scn_pitch_subj": "路演我们最新的 deck —— 拆穿护城河假设、单位经济和创始人-市场契合度。",
            "scn_audit_tag": "审查 · 找漏洞",
            "scn_audit_head": "对那份你差点上线的方案做一次对抗式审查",
            "scn_audit_body": "三位董事像要在生产环境里把它弄崩一样读你的方案 —— 阻断项、重大项、次要项，以及哪个假设最先崩。",
            "scn_audit_subj": "审查本季度的方案 —— 列出阻断项、重大项和次要项。哪个假设最先崩？",
            "scn_fork_tag": "决策 · 岔路",
            "scn_fork_head": "在两个真实选项之间，逼出一个选择",
            "scn_fork_body": "三位董事用不同的视角各为一条分支辩护 —— 成本、二阶效应、如果你错了意味着什么。到最后才决定。",
            "scn_fork_subj": "桌上有两个真实选项 —— 在真正重要的时间尺度上，每条分支会是什么样？我怎么判断自己错了？",
            // 未配置 API key 拦截
            "m_nokey_title": "请先配置 API key",
            "m_nokey_msg": "召集董事会需要一个模型密钥。请在「设置 → API keys」中添加后再试。",
            "m_nokey_go": "去配置 API keys",
            // 首次启动引导（5 步 · 对齐桌面版）
            "onb_step": "第 {n} / 5 步", "onb_back": "返回", "onb_continue": "继续",
            "onb_name_kicker": "00 · 入座", "onb_name_head": "这个房间该怎么称呼你？",
            "onb_name_sub": "从此刻起，这是属于你的房间。", "onb_name_ph": "比如 Kay", "onb_name_cta": "入座",
            "onb_phil_kicker": "01 · 是会议，不是聊天机器人",
            "onb_phil_head": "你召集一群固执的顾问，让他们当着你的面，为一个真正重要的问题争论。",
            "onb_phil_body": "三幕 · 召集 · 打磨 · 散会。你坐在主席位，董事们各执一词，散会时你带走一份纪要。",
            "onb_phil_note": "不是聊天机器人。董事们不会附和你 —— 他们会反复施压，直到问题变得锋利。",
            "onb_key_kicker": "02 · 交出一把钥匙", "onb_key_head": "选一个大脑 —— 或者全都要。",
            "onb_key_sub": "你的密钥只留在本机，我们绝不上传。",
            "onb_key_multi": "一把钥匙，所有模型", "onb_key_direct": "或者直连某家",
            "onb_key_field": "{provider} API 密钥", "onb_key_configured": "{provider} 密钥已配置",
            "onb_key_saving": "保存中…", "onb_key_fail": "这把密钥没能保存 —— 检查后重试。",
            "key_validate_empty": "请输入 API 密钥。",
            "key_validate_whitespace": "密钥里有空格 —— 粘贴时常会带上多余的空格，请删掉。",
            "key_validate_prefix": "{label} 的密钥应以 \u{201C}{prefix}\u{201D} 开头。",
            "key_validate_length": "对 {label} 来说太短了 —— 真实密钥至少有 {minLen} 个字符。",
            "onb_voice_kicker": "03 · 给他们一把声音 · 可选", "onb_voice_head": "想让他们开口说话吗？",
            "onb_voice_sub": "加一个 TTS 密钥，董事会就变成一张圆桌 —— 董事们入座，发言时抬头，倾听时退后。想纯文字也可以跳过，随时能在设置里打开。",
            "onb_voice_skip": "暂时跳过", "onb_voice_skipcta": "跳过", "onb_voice_save": "保存并继续",
            "onb_cast_kicker": "04 · 你的董事会",
            "onb_cast_head": "主席主持，董事们争论，纪要收尾。",
            "onb_cast_body": "默认由主席为你挑选三位董事，你也可以自己选。这个选择和你的问题，都在下一步的输入框里完成。",
            "onb_cast_preview": "预览 · 稍后在输入框里挑选", "onb_cast_flow": "下一步 · 在输入框里",
            "onb_cast_s1": "写下你的问题", "onb_cast_s2": "主席挑选 3 位董事", "onb_cast_s3": "点击召集",
            "onb_cast_cta": "我准备好了",
            "m_dir_most_used": "常用", "m_dir_all": "董事", "m_dir_rooms": "个房间",
            "m_dir_sort_newest": "最近创建", "m_dir_sort_oldest": "最早创建", "m_dir_sort_name": "名称",
            "m_rc_live": "进行中", "m_rc_paused": "已暂停", "m_rc_adjourned": "已闭会",
            "m_rc_voice": "语音", "m_rc_text": "文字", "m_rc_report_badge": "报告",
            "m_rc_meta": "{delivery} · {n} 位董事 · {ago}",
            "m_rc_meta_noago": "{delivery} · {n} 位董事",
            "connect_title": "连接到你的会议室",
            "connect_hint": "用 `boardroom --host 0.0.0.0` 启动桌面服务，然后在同一 Wi-Fi 下填入电脑地址。",
            "connect_btn": "连接", "connect_demo": "查看演示",
            "connect_connecting": "连接中…", "connect_bad": "地址格式不正确。",
            "m_room_back_aria": "返回房间", "m_room_menu_aria": "房间菜单",
            "m_dock_interject_aria": "举手发言", "m_dock_playpause_aria": "暂停 / 播放",
            "m_dock_rate_aria": "播放速度", "m_dock_collapse_aria": "收起控件", "m_dock_expand_aria": "展开控件",
            "m_queue_aria": "发言队列",
            "m_queue_title": "发言顺序",
            "m_queue_speaking": "正在发言", "m_queue_standby": "待命", "m_queue_done": "已发言", "m_queue_next": "下一位",
            "m_composer_ask": "向董事会提问…", "m_composer_clarify": "回复主席…",
            "m_send_fail": "发送失败 — 请重试。",
            "m_ask_q": "{who} 正在发言。现在打断，还是等轮到你？",
            "m_ask_interrupt": "立即打断", "m_ask_after": "在 {who} 之后", "m_ask_cancel": "取消",
            "m_adj_replay": "回放", "m_adj_followup": "追加房间", "m_adj_report": "报告", "m_adj_transcript": "记录",
            "m_adj_stop": "停止", "m_adj_followup_ph": "追问一个问题 — 用同一阵容召集新房间…",
            "m_adj_convening": "召集中…",
            "m_status_live": "进行中", "m_status_paused": "已暂停", "m_status_pausing": "暂停中", "m_status_resuming": "恢复中",
            "m_menu_title": "房间", "m_menu_settings": "房间设置", "m_menu_cast": "管理阵容",
            "m_menu_adjourn": "闭会并生成报告", "m_menu_genreport": "查看报告",
            "m_menu_pause": "暂停房间", "m_menu_resume": "恢复房间", "m_menu_delete": "删除房间",
            "m_menu_queue": "发言顺序",
            "m_sheet_queue": "队列", "m_queue_empty": "暂无排队发言。",
            "m_q_speaking": "发言中", "m_q_framing": "组织中", "m_q_up_next": "下一个", "m_q_spoke": "已发言",
            "m_q_round": "第 {n} 轮",
            "m_adjourn_file": "闭会并归档报告", "m_vote_adjourn": "发起投票",
            "m_adjourn_title": "闭会", "m_adjourn_format": "报告格式",
            "m_adjourn_supplement": "想强调什么?(可选)",
            "m_adjourn_supplement_ph": "例如:聚焦定价风险;结论先行",
            "m_adjourn_generate": "生成报告", "m_adjourn_end": "直接结束(不生成报告)",
            "m_round_reopen": "本轮结束 · 查看",
            "kp_eyebrow_vote": "▸ 关键观点 · 投票决定跟进方向",
            "kp_eyebrow_drafting": "▸ 关键观点 · 生成中…",
            "kp_eyebrow_degraded": "▸ 关键观点 · 未能从本轮发言中解析",
            "kp_vote_more": "跟进", "kp_vote_drop": "舍去",
            "kp_vote_aria_up": "感兴趣", "kp_vote_aria_down": "不感兴趣",
            "kp_shift_prefix": "▸ 主席建议 · 将语气切换为 ",
            "kp_switch_to": "切换为 {mode}", "kp_keep_mode": "保持 {mode}",
            "kp_mode_current": "当前", "kp_btn_adjourn": "闭会", "kp_vote_fail": "投票失败",
            "m_round_done": "本轮结束。", "m_continue": "继续", "m_kp_adjourn": "闭会",
            "m_round_sep": "第 {n} 轮",
            "m_chair_room_note": "议事提示", "m_chair_direct": "主席直话",
            "m_chair_pend_kicker": "主席", "m_chair_pend_default": "主席准备中",
            "m_chair_pend_clarify": "主席在审阅你的问题",
            "m_chair_pend_round_end": "主席在收束本轮",
            "m_chair_pend_convening": "主席在组建董事会",
            "m_tts_billing_title": "语音合成已暂停",
            "m_tts_billing_msg": "{provider} 提示余额不足，董事们无法朗读。请给 {provider} 充值，或在 设置 → API 密钥 里换一个语音 provider。",
            "m_tts_billing_recharge": "去充值", "m_tts_billing_dismiss": "知道了",
            "m_billing_title": "余额不足",
            "m_llm_billing_msg": "{provider} 提示余额不足或配额已用尽，董事们无法回应。请给 {provider} 充值，或在 设置 → API 密钥 里换一个 provider 的 key。",
            "m_provider_generic": "当前 provider",
            "m_chair_billing_kicker": "▸ 计费 · 需处理",
            "m_auth_title": "API key 被拒绝",
            "m_auth_msg": "provider 拒绝了该 API key —— 可能无效或已被删除。请在 设置 → API 密钥 里重新检查。",
            "m_auth_cta": "打开 API 密钥",
            "m_net_title": "网络超时",
            "m_net_msg": "未能及时连上模型 —— 网络波动或 provider 响应慢。点「重试」，或稍后再试。",
            "m_reconnect_title": "连接已断开",
            "m_reconnect_msg": "App 恢复后本地服务停止响应。点「重试」重新连接。",
            "m_brief_badge_generating": "正在生成报告…",
            "m_brief_badge_ready": "报告已就绪 · 点按查看",
            "m_brief_badge_failed": "报告生成失败 · 点按重试",
            "np_thinking": "思考中…", "np_in_session": "会议进行中",
            "rt_phase_next_speaker": "正在斟酌下一位发言…", "rt_phase_vote_summary": "正在综合本轮…",
            "rt_phase_searching": "正在检索…", "rt_phase_catching_up": "正在追上进度…",
            "rt_phase_clarify": "正在准备开场…", "rt_thinking_stalled": "长时间无响应，仍在等待",
            "m_delete_confirm": "删除\u{201C}{subject}\u{201D}？此操作不可撤销。", "m_delete_do": "删除",
            "m_nr_title": "新建房间", "m_nr_subject": "议题", "m_nr_subject_ph": "让董事会决定什么？",
            "m_nr_format": "形式", "m_nr_tone": "基调", "m_nr_board": "董事会",
            "m_nr_auto": "自动选择", "m_nr_auto_hint": "主席会根据你的议题从名册中组建董事会。",
            "m_nr_choose": "手选", "m_nr_choose_prompt": "选择董事",
            "m_nr_or_choose": "或手动选择董事", "m_nr_convene": "召集房间", "m_nr_convening": "召集中…",
            "m_nr_directors": "董事 · {n}", "m_dpick_done": "完成",
            "m_toast_pick_two": "至少选择两位董事。",
            // 新建董事
            "m_na_title": "新建董事", "m_na_desc_label": "描述",
            "m_na_desc_ph": "例如：一位冷峻的定价策略师，从单位经济学推演，鄙视虚荣指标——逼董事会说出决定一切的那个数字。",
            "m_na_build_mode": "构建模式", "m_na_signal": "速写", "m_na_signal_deck": "快速草稿 · 几秒",
            "m_na_full": "完整人格", "m_na_full_deck": "深度构建 · 联网佐证",
            "m_na_generate": "生成董事", "m_na_manual": "改为手动填写",
            "m_na_gen_fail": "生成失败 — 请用更具体的描述。", "m_na_generating": "正在起草董事…",
            "m_na_sig_step": "信号构建 · 第 {n} / {total} 步",
            "m_na_p1": "起草档案", "m_na_p2": "为董事命名", "m_na_p3": "撰写简介",
            "m_na_p4": "编写指令", "m_na_p5": "挑选模型嗓音", "m_na_p6": "润色",
            "m_na_name": "名字", "m_na_role": "角色标签", "m_na_intro_ph": "一句话说明其思考方式",
            "m_na_instr_ph": "角色 · 目标 · 声音 · 该董事应遵循的边界",
            "m_na_save": "保存董事", "m_na_saving": "保存中…",
            "m_na_avatar": "头像", "m_na_avatar_hint": "3D 头像 —— 骰子随机，点击可自定义。",
            "m_av_title": "自定义头像", "m_av_save": "使用",
            "m_av_model": "体型", "m_av_hair": "发型", "m_av_accessory": "配饰",
            "m_av_brow": "眉毛", "m_av_eye": "眼睛", "m_av_beard": "胡子",
            "m_av_tie": "领部", "m_av_top": "上装", "m_av_bottom": "下装",
            "m_av_c_skin": "肤色", "m_av_c_hair": "发色", "m_av_c_brow": "眉色",
            "m_av_c_beard": "胡色", "m_av_c_top": "上装色", "m_av_c_bottom": "下装色",
            "m_av_c_tie": "领部色", "m_av_c_eye": "瞳色",
            "m_av_customise": "自定义 3D 头像",
            // 3D avatar customiser · desktop parity (av3d_* · mirror avatar3d-editor.js)
            "av3d_kicker": "捏 avatar", "av3d_rand": "随机", "av3d_save": "保存", "av3d_cancel": "取消",
            "av3d_load_failed": "3D 形象没能加载。点击重试。", "av3d_retry": "重试",
            "av3d_sec_head": "头部", "av3d_sec_outfit": "服饰",
            "av3d_lab_skin": "肤色", "av3d_lab_hair": "发型", "av3d_lab_brow": "眼眉", "av3d_lab_beard": "胡子",
            "av3d_lab_eye": "眼睛", "av3d_lab_top": "上衣", "av3d_lab_bottom": "裤子", "av3d_lab_tie": "领带",
            "av3d_lab_accessory": "装饰",
            "av3d_opt_hairStyle_glasses": "丸子头", "av3d_opt_hairStyle_casual": "蓬松/乱发", "av3d_opt_hairStyle_street": "街头短发",
            "av3d_opt_hairStyle_royal": "中长发/刘海", "av3d_opt_hairStyle_xmas": "披肩长发", "av3d_opt_hairStyle_style6": "低马尾",
            "av3d_opt_hairStyle_style7": "短发偏分", "av3d_opt_hairStyle_style8": "熊熊短发", "av3d_opt_hairStyle_style9": "光头侧发",
            "av3d_opt_hairStyle_none": "无 (光头)",
            "av3d_opt_browStyle_default": "标准", "av3d_opt_browStyle_royal": "浓眉", "av3d_opt_browStyle_style6": "细眉",
            "av3d_opt_browStyle_style7": "柔眉", "av3d_opt_browStyle_style8": "粗眉",
            "av3d_opt_eyeStyle_default": "默认", "av3d_opt_eyeStyle_casual": "圆眼", "av3d_opt_eyeStyle_street": "细眼",
            "av3d_opt_eyeStyle_royal": "杏眼", "av3d_opt_eyeStyle_style7": "笑眼", "av3d_opt_eyeStyle_style8": "豆豆眼",
            "av3d_opt_eyeStyle_style9": "锐眼", "av3d_opt_eyeStyle_style10": "圆豆眼",
            "av3d_opt_beardStyle_none": "无", "av3d_opt_beardStyle_style8": "络腮胡", "av3d_opt_beardStyle_style9": "八字胡",
            "av3d_opt_beardStyle_style10": "皮卡丘小胡",
            "av3d_opt_tieStyle_none": "无", "av3d_opt_tieStyle_royal": "领带", "av3d_opt_tieStyle_xmas": "蝴蝶结",
            "av3d_opt_topStyle_glasses": "蓝色上衣", "av3d_opt_topStyle_casual": "黑T", "av3d_opt_topStyle_style6": "背心裙",
            "av3d_opt_topStyle_style7": "长袖",
            "av3d_opt_bottomStyle_casual": "白短裤", "av3d_opt_bottomStyle_street": "街头白短裤",
            "av3d_opt_accessory_none": "无", "av3d_opt_accessory_glasses": "眼镜", "av3d_opt_accessory_shades": "墨镜",
            "av3d_opt_accessory_headphones": "耳机", "av3d_opt_accessory_cap": "鸭舌帽", "av3d_opt_accessory_crown": "王冠",
            "av3d_opt_accessory_santa": "圣诞帽", "av3d_opt_accessory_tophat": "礼帽", "av3d_opt_accessory_mask": "口罩",
            "av3d_opt_accessory_blindfold": "眼罩", "av3d_opt_accessory_star": "星星", "av3d_opt_accessory_anger": "怒火",
            "av3d_opt_accessory_redcheek": "腮红", "av3d_opt_accessory_bearsuit": "熊熊连体", "av3d_opt_accessory_pikasuit": "皮卡丘外衣",
            "m_model_director": "董事模型", "m_model_director_hint": "驱动这位董事发言的 LLM。",
            "m_toast_describe_first": "请先描述这位董事。",
            "m_set_tone": "基调", "m_set_intensity": "强度",
            "m_set_delivery": "形式", "m_set_voice": "语音模式",
            "m_set_voice_sub": "朗读回复（TTS）。关闭后仅文字、无语音。",
            "m_set_vote": "投票环节",
            "m_vote_auto": "自动", "m_vote_manual": "手动",
            "m_vote_auto_sub": "主席在每轮结束时自动收尾并发起投票。",
            "m_vote_manual_sub": "董事会持续发言、不自动收尾——由你在合适时机手动发起投票。",
            "m_vote_end_round": "结束本轮并投票",
            "rt_vote_confirm_kicker": "本轮可结束", "rt_vote_confirm_q": "现在发起投票？",
            "rt_vote_confirm_go": "发起投票", "rt_vote_confirm_dismiss": "继续",
            "sa_head": "本场分析", "sa_stamp": "已闭会",
            "sa_tokens": "tokens", "sa_msgs": "消息", "sa_rounds": "轮次", "sa_duration": "时长",
            "sa_model_head": "模型用量", "sa_valued_head": "你认可的观点",
            "m_tone_brainstorm": "头脑风暴", "m_tone_constructive": "建设性", "m_tone_research": "研究",
            "m_tone_debate": "辩论", "m_tone_critique": "批判",
            "m_int_calm": "平和", "m_int_sharp": "犀利", "m_int_terse": "简练",
            "m_set_cast_save": "保存阵容", "m_set_cast_min": "至少保留一位董事。",
            "m_set_adjourned_note": "本房间已闭会 · 设置为只读。",
            "m_ap_title": "董事", "m_ap_moderator": "主席",
            "m_ap_radar": "能力雷达", "m_ap_brief": "工作纲要",
            "m_ap_activity": "活动", "m_ap_stat_rooms": "会议室", "m_ap_stat_rounds": "发言轮次",
            "m_ap_stat_tokens": "Token",
            "m_ap_available": "可用", "m_ap_model": "模型",
            "m_ap_bio": "简介", "m_ap_role": "角色", "m_ap_instruction": "指令",
            "m_ap_bio_empty": "暂无简介 —— 点「编辑」添加。", "m_ap_instr_empty": "暂无指令 —— 点「编辑」添加。",
            "m_ap_websearch": "联网搜索", "m_ap_websearch_sub": "允许该董事在会中实时查资料",
            "m_ap_edit": "编辑", "m_ap_save": "保存",
            "m_ap_rename": "重命名董事", "m_ap_name": "名字",
            "m_ap_del_dir": "删除董事", "m_ap_del_confirm": "删除 {name}？此操作不可撤销。",
            "m_ap_show_more": "展开", "m_ap_show_less": "收起",
            "m_ap_rules": "规则", "m_ap_rule_add": "添加规则", "m_ap_rule_ph": "一条原子约束…",
            "m_ap_mem_chair": "记忆 · 关于你", "m_ap_notes_none": "暂无笔记。",
            "m_ap_note_add": "添加笔记", "m_ap_note": "笔记",
            "m_ap_voice": "声音", "m_ap_voice_none": "未设置", "m_ap_voice_pick": "选择声音",
            "m_ap_voice_empty": "暂无可用声音 —— 请在设置里配置语音供应商。",
            "m_ap_emotion": "情绪", "m_ap_emotion_default": "默认",
            "m_ap_voice_preview": "试听声音", "m_ap_voice_stop": "停止", "m_ap_voice_loading": "加载中…",
            // Persona dossier（深度人格生成的董事）
            "m_dossier_title": "人格档案", "m_dossier_kicker": "人格 · 七阶构建",
            "m_dossier_built": "构建于 · {date}", "m_dossier_open": "打开档案",
            "m_dossier_concepts": "核心概念", "m_dossier_referents": "参照系", "m_dossier_rules": "行为准则",
            "m_dossier_voice": "示例", "m_dossier_checks": "自检项", "m_dossier_evals": "评测",
            "m_dossier_classified": "机密 · 董事人格档案",
            "m_dossier_spec": "人格规格", "m_dossier_lineage": "思想谱系",
            "m_dossier_loadbearing": "核心概念", "m_dossier_referentset": "参照系",
            "m_dossier_failure": "失败模式", "m_dossier_contrarian": "逆共识观点",
            "m_dossier_rules_h": "行为准则", "m_dossier_fewshot": "少样本示例",
            "m_dossier_reflection": "反思清单", "m_dossier_reflection_sub": "每轮发言前静默执行。",
            "m_dossier_eval": "评测集", "m_dossier_eval_sub": "测试提示 + 预期特征。",
            "m_dossier_example": "示例 {n}", "m_dossier_scenario": "场景",
            "m_dossier_generic": "通用 AI", "m_dossier_persona": "本董事",
            "m_dossier_rationale": "原因", "m_dossier_expected": "预期特征",
            "m_dossier_always": "总是", "m_dossier_never": "从不", "m_dossier_when": "当",
            "m_dossier_empty": "该董事并非通过深度人格管线生成。",
            "m_rep_title": "报告", "m_rep_loading": "加载报告中…", "m_rep_none": "这个房间还没有报告。",
            "m_rep_generating": "正在生成报告…", "m_rep_gen_btn": "生成报告",
            "m_prefs_title": "设置", "m_prefs_keys": "API 密钥", "m_prefs_usage": "用量", "m_prefs_language": "语言",
            "m_prefs_usage_sub": "{tokens} tokens · 本月",
            "m_prefs_avatar": "我的形象",
            "m_av_edit": "编辑形象",
            "m_av_foot": "你在房间里的 3D 形象。点击打开编辑器——选体型、发型、服装和配色。",
            // 用量面板
            "m_usage_title": "用量", "m_usage_total_sub": "tokens · 本月", "m_usage_by_model": "按模型",
            "m_usage_none": "暂无用量数据。", "m_usage_loading": "正在加载用量…",
            "m_usage_all": "全部 · 累计", "m_usage_cum": "累计", "m_usage_last14": "近 14 天",
            "m_usage_unit": "tokens", "m_usage_meta_models": "模型", "m_usage_meta_agents": "董事",
            "m_usage_meta_active": "活跃", "m_usage_top": "用量最高", "m_usage_chair": "主席",
            "m_usage_director": "董事", "m_usage_silent": "另有 {n} 位未消耗",
            "m_usage_retired": "{agents} 位已删除 · 已并入 {tokens} tokens", "m_usage_day_none": "当天无用量。",
            "m_lang_title": "语言",
            // API 密钥
            "m_keys_title": "API 密钥", "m_keys_none": "暂无密钥。", "m_keys_add": "添加密钥",
            "m_credetail_provider": "服务商", "m_credetail_status": "状态", "m_credetail_active": "使用中", "m_credetail_setactive": "设为使用中",
            "m_keys_foot": "密钥保存在你的 boardroom 服务器上。保存后只显示掩码预览——不再显示明文。点按某个密钥可将其设为该类别的启用项。",
            "m_cat_llm": "LLM 供应商", "m_cat_voice": "语音 · TTS", "m_cat_search": "联网搜索",
            "m_cat_llm_hint": "选择一个董事会每轮路由的供应商。载体一个 key 通达多个模型族；直连 key 只达一个族。",
            "m_cat_voice_hint": "实时语音房间的发声；启用的 key 驱动每位董事的语音。",
            "m_cat_search_hint": "让董事在研究基调的房间中引用实时来源。",
            "m_addkey_carriers": "载体 · 一个 key，多个模型", "m_addkey_direct": "直连供应商",
            "m_addkey_provider": "供应商", "m_addkey_label": "标签 · 可选", "m_addkey_label_ph": "如 个人、工作",
            "m_addkey_key": "API 密钥", "m_addkey_save": "保存密钥", "m_addkey_eye_aria": "显示或隐藏密钥",
            "m_toast_paste_key": "请先粘贴 API key。",
            // MiniMax 区域
            "m_addkey_group": "Group ID", "m_addkey_group_ph": "MiniMax GroupID（可选）",
            "m_addkey_group_hint": "仅当你的 MiniMax 密钥未内嵌 GroupID 时才需要填。克隆声音时必需。",
            "m_vc_group_needed_title": "需要 MiniMax Group ID",
            "m_vc_group_needed_msg": "克隆声音需要 MiniMax 的 GroupID。请到 设置 → API 密钥 → MiniMax 中填写后再试。",
            "m_addkey_region": "区域", "m_addkey_region_cn": "中国大陆", "m_addkey_region_intl": "海外",
            "m_addkey_region_cn_host": "api.minimaxi.com", "m_addkey_region_intl_host": "api.minimax.io",
            "m_addkey_region_hint": "选择你的 MiniMax 账号所属区域 —— platform.minimaxi.com 的密钥选「中国大陆」，platform.minimax.io 的选「海外」。",
            "common_done": "完成", "common_cancel": "取消", "common_retry": "重试", "common_server": "服务器", "common_ok": "好的",
        ],
    ]
}
