/**
 * Key points generated by the Chair at the end of each round. The user
 * votes 👍 / 👎 on each one; voted points feed back into the next
 * director system prompt as user-interest signals.
 */
import { newId } from "../utils/id.js";

import { getDb } from "./db.js";

export type KeyPointVote = "up" | "down" | null;

export interface KeyPoint {
  id: string;
  roomId: string;
  messageId: string | null;
  roundNum: number;
  body: string;
  vote: KeyPointVote;
  position: number;
  createdAt: number;
  votedAt: number | null;
}

interface Row {
  id: string;
  room_id: string;
  message_id: string | null;
  round_num: number;
  body: string;
  vote: string | null;
  position: number;
  created_at: number;
  voted_at: number | null;
}

const COLS =
  "id, room_id, message_id, round_num, body, vote, position, created_at, voted_at";

function mapRow(r: Row): KeyPoint {
  return {
    id: r.id,
    roomId: r.room_id,
    messageId: r.message_id,
    roundNum: r.round_num,
    body: r.body,
    vote: r.vote === "up" ? "up" : r.vote === "down" ? "down" : null,
    position: r.position,
    createdAt: r.created_at,
    votedAt: r.voted_at,
  };
}

export interface InsertKeyPoint {
  roomId: string;
  messageId: string | null;
  roundNum: number;
  body: string;
  position: number;
}

export function insertKeyPoint(p: InsertKeyPoint): KeyPoint {
  const id = "kp_" + newId();
  const now = Date.now();
  getDb()
    .prepare(
      `INSERT INTO key_points (id, room_id, message_id, round_num, body, vote, position, created_at, voted_at)
       VALUES (?, ?, ?, ?, ?, NULL, ?, ?, NULL)`,
    )
    .run(id, p.roomId, p.messageId, p.roundNum, p.body, p.position, now);
  return getKeyPoint(id)!;
}

export function getKeyPoint(id: string): KeyPoint | null {
  const r = getDb().prepare(`SELECT ${COLS} FROM key_points WHERE id = ?`).get(id) as Row | undefined;
  return r ? mapRow(r) : null;
}

export function listKeyPointsForRoom(roomId: string): KeyPoint[] {
  const rows = getDb()
    .prepare(`SELECT ${COLS} FROM key_points WHERE room_id = ? ORDER BY round_num ASC, position ASC`)
    .all(roomId) as Row[];
  return rows.map(mapRow);
}

/** Replace the user's vote on a single key point. Returns the updated row. */
export function setKeyPointVote(id: string, vote: KeyPointVote): KeyPoint | null {
  const now = Date.now();
  getDb()
    .prepare(`UPDATE key_points SET vote = ?, voted_at = ? WHERE id = ?`)
    .run(vote, vote === null ? null : now, id);
  return getKeyPoint(id);
}
